# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.secret_response import SecretResponse

class TestSecretResponse(unittest.TestCase):
    """SecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretResponse:
        """Test SecretResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretResponse`
        """
        model = SecretResponse()
        if include_optional:
            return SecretResponse(
                agent_name = '',
                agent_names = [
                    ''
                    ],
                attached_agents = 56,
                created_at = '',
                keys = [
                    ''
                    ],
                managed = True,
                name = '',
                namespace = ''
            )
        else:
            return SecretResponse(
        )
        """

    def testSecretResponse(self):
        """Test SecretResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
