# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.schedule_response import ScheduleResponse

class TestScheduleResponse(unittest.TestCase):
    """ScheduleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleResponse:
        """Test ScheduleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleResponse`
        """
        model = ScheduleResponse()
        if include_optional:
            return ScheduleResponse(
                agent_name = '',
                auto_delete = True,
                created_at = '',
                failed_runs = 56,
                keep_agents = True,
                last_run_cost_usd = '',
                last_run_status = '',
                last_run_time = '',
                last_run_tokens = 56,
                name = '',
                namespace = '',
                next_run_time = '',
                phase = '',
                run_count = 56,
                schedule = '',
                successful_runs = 56,
                timezone = '',
                total_cost_usd = '',
                total_tokens = 56
            )
        else:
            return ScheduleResponse(
        )
        """

    def testScheduleResponse(self):
        """Test ScheduleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
