# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.patch_agent_request import PatchAgentRequest

class TestPatchAgentRequest(unittest.TestCase):
    """PatchAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchAgentRequest:
        """Test PatchAgentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchAgentRequest`
        """
        model = PatchAgentRequest()
        if include_optional:
            return PatchAgentRequest(
                connectors = [
                    ''
                    ],
                instructions = '',
                lifecycle = '',
                memories = [
                    ''
                    ],
                model = '',
                secret_refs = [
                    ''
                    ],
                skills = [
                    ''
                    ],
                system_prompt = '',
                template_ref = ''
            )
        else:
            return PatchAgentRequest(
        )
        """

    def testPatchAgentRequest(self):
        """Test PatchAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
