# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.secret_list_response import SecretListResponse

class TestSecretListResponse(unittest.TestCase):
    """SecretListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretListResponse:
        """Test SecretListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretListResponse`
        """
        model = SecretListResponse()
        if include_optional:
            return SecretListResponse(
                secrets = [
                    {"createdAt":"createdAt","keys":["keys","keys"],"managed":true,"agentNames":["agentNames","agentNames"],"name":"name","namespace":"namespace","agentName":"agentName","attachedAgents":0}
                    ]
            )
        else:
            return SecretListResponse(
        )
        """

    def testSecretListResponse(self):
        """Test SecretListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
