# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.patch_schedule_request import PatchScheduleRequest

class TestPatchScheduleRequest(unittest.TestCase):
    """PatchScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchScheduleRequest:
        """Test PatchScheduleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchScheduleRequest`
        """
        model = PatchScheduleRequest()
        if include_optional:
            return PatchScheduleRequest(
                schedule = ''
            )
        else:
            return PatchScheduleRequest(
        )
        """

    def testPatchScheduleRequest(self):
        """Test PatchScheduleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
