# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List agent templates
        """
        pass

    def test_namespaces_get(self) -> None:
        """Test case for namespaces_get

        List namespaces
        """
        pass


if __name__ == '__main__':
    unittest.main()
