# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_agents_name_ws_get(self) -> None:
        """Test case for agents_name_ws_get

        Stream agent events (WebSocket)
        """
        pass

    def test_cancel_agent_task(self) -> None:
        """Test case for cancel_agent_task

        Cancel agent task
        """
        pass

    def test_create_agent(self) -> None:
        """Test case for create_agent

        Create agent or send task
        """
        pass

    def test_delete_agent(self) -> None:
        """Test case for delete_agent

        Delete agent
        """
        pass

    def test_get_agent(self) -> None:
        """Test case for get_agent

        Get agent details
        """
        pass

    def test_get_agent_events(self) -> None:
        """Test case for get_agent_events

        Get agent events
        """
        pass

    def test_list_agents(self) -> None:
        """Test case for list_agents

        List agents
        """
        pass

    def test_patch_agent(self) -> None:
        """Test case for patch_agent

        Patch agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
