# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.api.offices_api import OfficesApi


class TestOfficesApi(unittest.TestCase):
    """OfficesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OfficesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_office(self) -> None:
        """Test case for delete_office

        Delete office
        """
        pass

    def test_get_office(self) -> None:
        """Test case for get_office

        Get office details
        """
        pass

    def test_get_office_events(self) -> None:
        """Test case for get_office_events

        Get office events
        """
        pass

    def test_list_offices(self) -> None:
        """Test case for list_offices

        List offices
        """
        pass


if __name__ == '__main__':
    unittest.main()
