# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.schedule_list_response import ScheduleListResponse

class TestScheduleListResponse(unittest.TestCase):
    """ScheduleListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleListResponse:
        """Test ScheduleListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleListResponse`
        """
        model = ScheduleListResponse()
        if include_optional:
            return ScheduleListResponse(
                schedules = [
                    {"phase":"phase","successfulRuns":5,"timezone":"timezone","totalCostUSD":"totalCostUSD","lastRunStatus":"lastRunStatus","agentName":"agentName","failedRuns":0,"lastRunCostUSD":"lastRunCostUSD","totalTokens":5,"lastRunTokens":6,"createdAt":"createdAt","schedule":"schedule","lastRunTime":"lastRunTime","nextRunTime":"nextRunTime","autoDelete":true,"name":"name","namespace":"namespace","keepAgents":true,"runCount":1}
                    ]
            )
        else:
            return ScheduleListResponse(
        )
        """

    def testScheduleListResponse(self):
        """Test ScheduleListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
