# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.create_connector_request import CreateConnectorRequest

class TestCreateConnectorRequest(unittest.TestCase):
    """CreateConnectorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConnectorRequest:
        """Test CreateConnectorRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConnectorRequest`
        """
        model = CreateConnectorRequest()
        if include_optional:
            return CreateConnectorRequest(
                auth_secret_key = '',
                auth_secret_name = '',
                auth_type = '',
                display_name = '',
                name = '',
                namespace = '',
                oauth_client_id = '',
                oauth_client_secret = '',
                service = '',
                type = '',
                url = ''
            )
        else:
            return CreateConnectorRequest(
                name = '',
                service = '',
                url = '',
        )
        """

    def testCreateConnectorRequest(self):
        """Test CreateConnectorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
