# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.create_schedule_request import CreateScheduleRequest

class TestCreateScheduleRequest(unittest.TestCase):
    """CreateScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateScheduleRequest:
        """Test CreateScheduleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateScheduleRequest`
        """
        model = CreateScheduleRequest()
        if include_optional:
            return CreateScheduleRequest(
                agent = komputer_ai.models.create_schedule_agent_spec.CreateScheduleAgentSpec(
                    lifecycle = '', 
                    model = '', 
                    role = '', 
                    secret_refs = [
                        ''
                        ], 
                    template_ref = '', ),
                agent_name = '',
                auto_delete = True,
                instructions = '',
                keep_agents = True,
                name = '',
                namespace = '',
                schedule = '',
                timezone = ''
            )
        else:
            return CreateScheduleRequest(
                instructions = '',
                name = '',
                schedule = '',
        )
        """

    def testCreateScheduleRequest(self):
        """Test CreateScheduleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
