# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.models.agent_response import AgentResponse

class TestAgentResponse(unittest.TestCase):
    """AgentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentResponse:
        """Test AgentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentResponse`
        """
        model = AgentResponse()
        if include_optional:
            return AgentResponse(
                connectors = [
                    ''
                    ],
                created_at = '',
                instructions = '',
                last_task_cost_usd = '',
                last_task_message = '',
                lifecycle = '',
                memories = [
                    ''
                    ],
                model = '',
                model_context_window = 56,
                name = '',
                namespace = '',
                secrets = [
                    ''
                    ],
                skills = [
                    ''
                    ],
                status = '',
                system_prompt = '',
                task_status = '',
                total_cost_usd = '',
                total_tokens = 56
            )
        else:
            return AgentResponse(
        )
        """

    def testAgentResponse(self):
        """Test AgentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
