# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from komputer_ai.api.schedules_api import SchedulesApi


class TestSchedulesApi(unittest.TestCase):
    """SchedulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchedulesApi()

    def tearDown(self) -> None:
        pass

    def test_create_schedule(self) -> None:
        """Test case for create_schedule

        Create schedule
        """
        pass

    def test_delete_schedule(self) -> None:
        """Test case for delete_schedule

        Delete schedule
        """
        pass

    def test_get_schedule(self) -> None:
        """Test case for get_schedule

        Get schedule details
        """
        pass

    def test_list_schedules(self) -> None:
        """Test case for list_schedules

        List schedules
        """
        pass

    def test_patch_schedule(self) -> None:
        """Test case for patch_schedule

        Patch schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
