{{- if and .Values.ui.enabled .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.ingress.className }}
  ingressClassName: {{ .Values.ui.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ui.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Release.Name }}-ui
            port:
              number: {{ $.Values.ui.service.port }}
      {{- end }}
  {{- end }}
  {{- with .Values.ui.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
