/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the TriggerScheduleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerScheduleResponse{}

// TriggerScheduleResponse struct for TriggerScheduleResponse
type TriggerScheduleResponse struct {
	AgentName *string `json:"agentName,omitempty"`
	Name *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewTriggerScheduleResponse instantiates a new TriggerScheduleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerScheduleResponse() *TriggerScheduleResponse {
	this := TriggerScheduleResponse{}
	return &this
}

// NewTriggerScheduleResponseWithDefaults instantiates a new TriggerScheduleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerScheduleResponseWithDefaults() *TriggerScheduleResponse {
	this := TriggerScheduleResponse{}
	return &this
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *TriggerScheduleResponse) GetAgentName() string {
	if o == nil || IsNil(o.AgentName) {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerScheduleResponse) GetAgentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentName) {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *TriggerScheduleResponse) HasAgentName() bool {
	if o != nil && !IsNil(o.AgentName) {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *TriggerScheduleResponse) SetAgentName(v string) {
	o.AgentName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TriggerScheduleResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerScheduleResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TriggerScheduleResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TriggerScheduleResponse) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TriggerScheduleResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerScheduleResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TriggerScheduleResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TriggerScheduleResponse) SetStatus(v string) {
	o.Status = &v
}

func (o TriggerScheduleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerScheduleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentName) {
		toSerialize["agentName"] = o.AgentName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableTriggerScheduleResponse struct {
	value *TriggerScheduleResponse
	isSet bool
}

func (v NullableTriggerScheduleResponse) Get() *TriggerScheduleResponse {
	return v.value
}

func (v *NullableTriggerScheduleResponse) Set(val *TriggerScheduleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerScheduleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerScheduleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerScheduleResponse(val *TriggerScheduleResponse) *NullableTriggerScheduleResponse {
	return &NullableTriggerScheduleResponse{value: val, isSet: true}
}

func (v NullableTriggerScheduleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerScheduleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


