/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the AddSquadMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddSquadMemberRequest{}

// AddSquadMemberRequest struct for AddSquadMemberRequest
type AddSquadMemberRequest struct {
	Ref *V1alpha1KomputerSquadMemberRef `json:"ref,omitempty"`
	Spec *V1alpha1KomputerAgentSpec `json:"spec,omitempty"`
}

// NewAddSquadMemberRequest instantiates a new AddSquadMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddSquadMemberRequest() *AddSquadMemberRequest {
	this := AddSquadMemberRequest{}
	return &this
}

// NewAddSquadMemberRequestWithDefaults instantiates a new AddSquadMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddSquadMemberRequestWithDefaults() *AddSquadMemberRequest {
	this := AddSquadMemberRequest{}
	return &this
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *AddSquadMemberRequest) GetRef() V1alpha1KomputerSquadMemberRef {
	if o == nil || IsNil(o.Ref) {
		var ret V1alpha1KomputerSquadMemberRef
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSquadMemberRequest) GetRefOk() (*V1alpha1KomputerSquadMemberRef, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *AddSquadMemberRequest) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given V1alpha1KomputerSquadMemberRef and assigns it to the Ref field.
func (o *AddSquadMemberRequest) SetRef(v V1alpha1KomputerSquadMemberRef) {
	o.Ref = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AddSquadMemberRequest) GetSpec() V1alpha1KomputerAgentSpec {
	if o == nil || IsNil(o.Spec) {
		var ret V1alpha1KomputerAgentSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSquadMemberRequest) GetSpecOk() (*V1alpha1KomputerAgentSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AddSquadMemberRequest) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given V1alpha1KomputerAgentSpec and assigns it to the Spec field.
func (o *AddSquadMemberRequest) SetSpec(v V1alpha1KomputerAgentSpec) {
	o.Spec = &v
}

func (o AddSquadMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddSquadMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableAddSquadMemberRequest struct {
	value *AddSquadMemberRequest
	isSet bool
}

func (v NullableAddSquadMemberRequest) Get() *AddSquadMemberRequest {
	return v.value
}

func (v *NullableAddSquadMemberRequest) Set(val *AddSquadMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddSquadMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddSquadMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddSquadMemberRequest(val *AddSquadMemberRequest) *NullableAddSquadMemberRequest {
	return &NullableAddSquadMemberRequest{value: val, isSet: true}
}

func (v NullableAddSquadMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddSquadMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


