/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the PatchScheduleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchScheduleRequest{}

// PatchScheduleRequest struct for PatchScheduleRequest
type PatchScheduleRequest struct {
	Agent *CreateScheduleAgentSpec `json:"agent,omitempty"`
	AgentName *string `json:"agentName,omitempty"`
	AutoDelete *bool `json:"autoDelete,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
	KeepAgents *bool `json:"keepAgents,omitempty"`
	Schedule *string `json:"schedule,omitempty"`
	Suspended *bool `json:"suspended,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// NewPatchScheduleRequest instantiates a new PatchScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchScheduleRequest() *PatchScheduleRequest {
	this := PatchScheduleRequest{}
	return &this
}

// NewPatchScheduleRequestWithDefaults instantiates a new PatchScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchScheduleRequestWithDefaults() *PatchScheduleRequest {
	this := PatchScheduleRequest{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetAgent() CreateScheduleAgentSpec {
	if o == nil || IsNil(o.Agent) {
		var ret CreateScheduleAgentSpec
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetAgentOk() (*CreateScheduleAgentSpec, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given CreateScheduleAgentSpec and assigns it to the Agent field.
func (o *PatchScheduleRequest) SetAgent(v CreateScheduleAgentSpec) {
	o.Agent = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetAgentName() string {
	if o == nil || IsNil(o.AgentName) {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetAgentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentName) {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasAgentName() bool {
	if o != nil && !IsNil(o.AgentName) {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *PatchScheduleRequest) SetAgentName(v string) {
	o.AgentName = &v
}

// GetAutoDelete returns the AutoDelete field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetAutoDelete() bool {
	if o == nil || IsNil(o.AutoDelete) {
		var ret bool
		return ret
	}
	return *o.AutoDelete
}

// GetAutoDeleteOk returns a tuple with the AutoDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetAutoDeleteOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoDelete) {
		return nil, false
	}
	return o.AutoDelete, true
}

// HasAutoDelete returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasAutoDelete() bool {
	if o != nil && !IsNil(o.AutoDelete) {
		return true
	}

	return false
}

// SetAutoDelete gets a reference to the given bool and assigns it to the AutoDelete field.
func (o *PatchScheduleRequest) SetAutoDelete(v bool) {
	o.AutoDelete = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *PatchScheduleRequest) SetInstructions(v string) {
	o.Instructions = &v
}

// GetKeepAgents returns the KeepAgents field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetKeepAgents() bool {
	if o == nil || IsNil(o.KeepAgents) {
		var ret bool
		return ret
	}
	return *o.KeepAgents
}

// GetKeepAgentsOk returns a tuple with the KeepAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetKeepAgentsOk() (*bool, bool) {
	if o == nil || IsNil(o.KeepAgents) {
		return nil, false
	}
	return o.KeepAgents, true
}

// HasKeepAgents returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasKeepAgents() bool {
	if o != nil && !IsNil(o.KeepAgents) {
		return true
	}

	return false
}

// SetKeepAgents gets a reference to the given bool and assigns it to the KeepAgents field.
func (o *PatchScheduleRequest) SetKeepAgents(v bool) {
	o.KeepAgents = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *PatchScheduleRequest) SetSchedule(v string) {
	o.Schedule = &v
}

// GetSuspended returns the Suspended field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetSuspended() bool {
	if o == nil || IsNil(o.Suspended) {
		var ret bool
		return ret
	}
	return *o.Suspended
}

// GetSuspendedOk returns a tuple with the Suspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetSuspendedOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspended) {
		return nil, false
	}
	return o.Suspended, true
}

// HasSuspended returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasSuspended() bool {
	if o != nil && !IsNil(o.Suspended) {
		return true
	}

	return false
}

// SetSuspended gets a reference to the given bool and assigns it to the Suspended field.
func (o *PatchScheduleRequest) SetSuspended(v bool) {
	o.Suspended = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *PatchScheduleRequest) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchScheduleRequest) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *PatchScheduleRequest) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *PatchScheduleRequest) SetTimezone(v string) {
	o.Timezone = &v
}

func (o PatchScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	if !IsNil(o.AgentName) {
		toSerialize["agentName"] = o.AgentName
	}
	if !IsNil(o.AutoDelete) {
		toSerialize["autoDelete"] = o.AutoDelete
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.KeepAgents) {
		toSerialize["keepAgents"] = o.KeepAgents
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Suspended) {
		toSerialize["suspended"] = o.Suspended
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	return toSerialize, nil
}

type NullablePatchScheduleRequest struct {
	value *PatchScheduleRequest
	isSet bool
}

func (v NullablePatchScheduleRequest) Get() *PatchScheduleRequest {
	return v.value
}

func (v *NullablePatchScheduleRequest) Set(val *PatchScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchScheduleRequest(val *PatchScheduleRequest) *NullablePatchScheduleRequest {
	return &NullablePatchScheduleRequest{value: val, isSet: true}
}

func (v NullablePatchScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


