/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the CompactAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompactAgentRequest{}

// CompactAgentRequest struct for CompactAgentRequest
type CompactAgentRequest struct {
	Instructions *string `json:"instructions,omitempty"`
}

// NewCompactAgentRequest instantiates a new CompactAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompactAgentRequest() *CompactAgentRequest {
	this := CompactAgentRequest{}
	return &this
}

// NewCompactAgentRequestWithDefaults instantiates a new CompactAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompactAgentRequestWithDefaults() *CompactAgentRequest {
	this := CompactAgentRequest{}
	return &this
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *CompactAgentRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompactAgentRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *CompactAgentRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *CompactAgentRequest) SetInstructions(v string) {
	o.Instructions = &v
}

func (o CompactAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompactAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	return toSerialize, nil
}

type NullableCompactAgentRequest struct {
	value *CompactAgentRequest
	isSet bool
}

func (v NullableCompactAgentRequest) Get() *CompactAgentRequest {
	return v.value
}

func (v *NullableCompactAgentRequest) Set(val *CompactAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompactAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompactAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompactAgentRequest(val *CompactAgentRequest) *NullableCompactAgentRequest {
	return &NullableCompactAgentRequest{value: val, isSet: true}
}

func (v NullableCompactAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompactAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


