/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the SquadMemberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SquadMemberResponse{}

// SquadMemberResponse struct for SquadMemberResponse
type SquadMemberResponse struct {
	Name *string `json:"name,omitempty"`
	Ready *bool `json:"ready,omitempty"`
	TaskStatus *string `json:"taskStatus,omitempty"`
}

// NewSquadMemberResponse instantiates a new SquadMemberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSquadMemberResponse() *SquadMemberResponse {
	this := SquadMemberResponse{}
	return &this
}

// NewSquadMemberResponseWithDefaults instantiates a new SquadMemberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSquadMemberResponseWithDefaults() *SquadMemberResponse {
	this := SquadMemberResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SquadMemberResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadMemberResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SquadMemberResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SquadMemberResponse) SetName(v string) {
	o.Name = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *SquadMemberResponse) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadMemberResponse) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *SquadMemberResponse) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *SquadMemberResponse) SetReady(v bool) {
	o.Ready = &v
}

// GetTaskStatus returns the TaskStatus field value if set, zero value otherwise.
func (o *SquadMemberResponse) GetTaskStatus() string {
	if o == nil || IsNil(o.TaskStatus) {
		var ret string
		return ret
	}
	return *o.TaskStatus
}

// GetTaskStatusOk returns a tuple with the TaskStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadMemberResponse) GetTaskStatusOk() (*string, bool) {
	if o == nil || IsNil(o.TaskStatus) {
		return nil, false
	}
	return o.TaskStatus, true
}

// HasTaskStatus returns a boolean if a field has been set.
func (o *SquadMemberResponse) HasTaskStatus() bool {
	if o != nil && !IsNil(o.TaskStatus) {
		return true
	}

	return false
}

// SetTaskStatus gets a reference to the given string and assigns it to the TaskStatus field.
func (o *SquadMemberResponse) SetTaskStatus(v string) {
	o.TaskStatus = &v
}

func (o SquadMemberResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SquadMemberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.TaskStatus) {
		toSerialize["taskStatus"] = o.TaskStatus
	}
	return toSerialize, nil
}

type NullableSquadMemberResponse struct {
	value *SquadMemberResponse
	isSet bool
}

func (v NullableSquadMemberResponse) Get() *SquadMemberResponse {
	return v.value
}

func (v *NullableSquadMemberResponse) Set(val *SquadMemberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSquadMemberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSquadMemberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSquadMemberResponse(val *SquadMemberResponse) *NullableSquadMemberResponse {
	return &NullableSquadMemberResponse{value: val, isSet: true}
}

func (v NullableSquadMemberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSquadMemberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


