/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the CostBreakdownResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostBreakdownResponse{}

// CostBreakdownResponse struct for CostBreakdownResponse
type CostBreakdownResponse struct {
	Agent *string `json:"agent,omitempty"`
	CachedAt *string `json:"cachedAt,omitempty"`
	TaskCount *int32 `json:"taskCount,omitempty"`
	Tasks []TaskBreakdown `json:"tasks,omitempty"`
	TotalCost *float32 `json:"totalCost,omitempty"`
}

// NewCostBreakdownResponse instantiates a new CostBreakdownResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostBreakdownResponse() *CostBreakdownResponse {
	this := CostBreakdownResponse{}
	return &this
}

// NewCostBreakdownResponseWithDefaults instantiates a new CostBreakdownResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostBreakdownResponseWithDefaults() *CostBreakdownResponse {
	this := CostBreakdownResponse{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *CostBreakdownResponse) GetAgent() string {
	if o == nil || IsNil(o.Agent) {
		var ret string
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostBreakdownResponse) GetAgentOk() (*string, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *CostBreakdownResponse) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given string and assigns it to the Agent field.
func (o *CostBreakdownResponse) SetAgent(v string) {
	o.Agent = &v
}

// GetCachedAt returns the CachedAt field value if set, zero value otherwise.
func (o *CostBreakdownResponse) GetCachedAt() string {
	if o == nil || IsNil(o.CachedAt) {
		var ret string
		return ret
	}
	return *o.CachedAt
}

// GetCachedAtOk returns a tuple with the CachedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostBreakdownResponse) GetCachedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CachedAt) {
		return nil, false
	}
	return o.CachedAt, true
}

// HasCachedAt returns a boolean if a field has been set.
func (o *CostBreakdownResponse) HasCachedAt() bool {
	if o != nil && !IsNil(o.CachedAt) {
		return true
	}

	return false
}

// SetCachedAt gets a reference to the given string and assigns it to the CachedAt field.
func (o *CostBreakdownResponse) SetCachedAt(v string) {
	o.CachedAt = &v
}

// GetTaskCount returns the TaskCount field value if set, zero value otherwise.
func (o *CostBreakdownResponse) GetTaskCount() int32 {
	if o == nil || IsNil(o.TaskCount) {
		var ret int32
		return ret
	}
	return *o.TaskCount
}

// GetTaskCountOk returns a tuple with the TaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostBreakdownResponse) GetTaskCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TaskCount) {
		return nil, false
	}
	return o.TaskCount, true
}

// HasTaskCount returns a boolean if a field has been set.
func (o *CostBreakdownResponse) HasTaskCount() bool {
	if o != nil && !IsNil(o.TaskCount) {
		return true
	}

	return false
}

// SetTaskCount gets a reference to the given int32 and assigns it to the TaskCount field.
func (o *CostBreakdownResponse) SetTaskCount(v int32) {
	o.TaskCount = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *CostBreakdownResponse) GetTasks() []TaskBreakdown {
	if o == nil || IsNil(o.Tasks) {
		var ret []TaskBreakdown
		return ret
	}
	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostBreakdownResponse) GetTasksOk() ([]TaskBreakdown, bool) {
	if o == nil || IsNil(o.Tasks) {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *CostBreakdownResponse) HasTasks() bool {
	if o != nil && !IsNil(o.Tasks) {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []TaskBreakdown and assigns it to the Tasks field.
func (o *CostBreakdownResponse) SetTasks(v []TaskBreakdown) {
	o.Tasks = v
}

// GetTotalCost returns the TotalCost field value if set, zero value otherwise.
func (o *CostBreakdownResponse) GetTotalCost() float32 {
	if o == nil || IsNil(o.TotalCost) {
		var ret float32
		return ret
	}
	return *o.TotalCost
}

// GetTotalCostOk returns a tuple with the TotalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostBreakdownResponse) GetTotalCostOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCost) {
		return nil, false
	}
	return o.TotalCost, true
}

// HasTotalCost returns a boolean if a field has been set.
func (o *CostBreakdownResponse) HasTotalCost() bool {
	if o != nil && !IsNil(o.TotalCost) {
		return true
	}

	return false
}

// SetTotalCost gets a reference to the given float32 and assigns it to the TotalCost field.
func (o *CostBreakdownResponse) SetTotalCost(v float32) {
	o.TotalCost = &v
}

func (o CostBreakdownResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostBreakdownResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	if !IsNil(o.CachedAt) {
		toSerialize["cachedAt"] = o.CachedAt
	}
	if !IsNil(o.TaskCount) {
		toSerialize["taskCount"] = o.TaskCount
	}
	if !IsNil(o.Tasks) {
		toSerialize["tasks"] = o.Tasks
	}
	if !IsNil(o.TotalCost) {
		toSerialize["totalCost"] = o.TotalCost
	}
	return toSerialize, nil
}

type NullableCostBreakdownResponse struct {
	value *CostBreakdownResponse
	isSet bool
}

func (v NullableCostBreakdownResponse) Get() *CostBreakdownResponse {
	return v.value
}

func (v *NullableCostBreakdownResponse) Set(val *CostBreakdownResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCostBreakdownResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCostBreakdownResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostBreakdownResponse(val *CostBreakdownResponse) *NullableCostBreakdownResponse {
	return &NullableCostBreakdownResponse{value: val, isSet: true}
}

func (v NullableCostBreakdownResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostBreakdownResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


