/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the TaskBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskBreakdown{}

// TaskBreakdown struct for TaskBreakdown
type TaskBreakdown struct {
	CacheCreateTokens *int32 `json:"cacheCreateTokens,omitempty"`
	CacheReadTokens *int32 `json:"cacheReadTokens,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
	CostUSD *float32 `json:"costUSD,omitempty"`
	DurationMs *int32 `json:"durationMs,omitempty"`
	Events []AgentEvent `json:"events,omitempty"`
	Index *int32 `json:"index,omitempty"`
	InputTokens *int32 `json:"inputTokens,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	OutputTokens *int32 `json:"outputTokens,omitempty"`
	StartedAt *string `json:"startedAt,omitempty"`
	Steer *bool `json:"steer,omitempty"`
	Turns *int32 `json:"turns,omitempty"`
}

// NewTaskBreakdown instantiates a new TaskBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskBreakdown() *TaskBreakdown {
	this := TaskBreakdown{}
	return &this
}

// NewTaskBreakdownWithDefaults instantiates a new TaskBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskBreakdownWithDefaults() *TaskBreakdown {
	this := TaskBreakdown{}
	return &this
}

// GetCacheCreateTokens returns the CacheCreateTokens field value if set, zero value otherwise.
func (o *TaskBreakdown) GetCacheCreateTokens() int32 {
	if o == nil || IsNil(o.CacheCreateTokens) {
		var ret int32
		return ret
	}
	return *o.CacheCreateTokens
}

// GetCacheCreateTokensOk returns a tuple with the CacheCreateTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetCacheCreateTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.CacheCreateTokens) {
		return nil, false
	}
	return o.CacheCreateTokens, true
}

// HasCacheCreateTokens returns a boolean if a field has been set.
func (o *TaskBreakdown) HasCacheCreateTokens() bool {
	if o != nil && !IsNil(o.CacheCreateTokens) {
		return true
	}

	return false
}

// SetCacheCreateTokens gets a reference to the given int32 and assigns it to the CacheCreateTokens field.
func (o *TaskBreakdown) SetCacheCreateTokens(v int32) {
	o.CacheCreateTokens = &v
}

// GetCacheReadTokens returns the CacheReadTokens field value if set, zero value otherwise.
func (o *TaskBreakdown) GetCacheReadTokens() int32 {
	if o == nil || IsNil(o.CacheReadTokens) {
		var ret int32
		return ret
	}
	return *o.CacheReadTokens
}

// GetCacheReadTokensOk returns a tuple with the CacheReadTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetCacheReadTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.CacheReadTokens) {
		return nil, false
	}
	return o.CacheReadTokens, true
}

// HasCacheReadTokens returns a boolean if a field has been set.
func (o *TaskBreakdown) HasCacheReadTokens() bool {
	if o != nil && !IsNil(o.CacheReadTokens) {
		return true
	}

	return false
}

// SetCacheReadTokens gets a reference to the given int32 and assigns it to the CacheReadTokens field.
func (o *TaskBreakdown) SetCacheReadTokens(v int32) {
	o.CacheReadTokens = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *TaskBreakdown) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt) {
		var ret string
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetCompletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *TaskBreakdown) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given string and assigns it to the CompletedAt field.
func (o *TaskBreakdown) SetCompletedAt(v string) {
	o.CompletedAt = &v
}

// GetCostUSD returns the CostUSD field value if set, zero value otherwise.
func (o *TaskBreakdown) GetCostUSD() float32 {
	if o == nil || IsNil(o.CostUSD) {
		var ret float32
		return ret
	}
	return *o.CostUSD
}

// GetCostUSDOk returns a tuple with the CostUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetCostUSDOk() (*float32, bool) {
	if o == nil || IsNil(o.CostUSD) {
		return nil, false
	}
	return o.CostUSD, true
}

// HasCostUSD returns a boolean if a field has been set.
func (o *TaskBreakdown) HasCostUSD() bool {
	if o != nil && !IsNil(o.CostUSD) {
		return true
	}

	return false
}

// SetCostUSD gets a reference to the given float32 and assigns it to the CostUSD field.
func (o *TaskBreakdown) SetCostUSD(v float32) {
	o.CostUSD = &v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *TaskBreakdown) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs) {
		var ret int32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetDurationMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *TaskBreakdown) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int32 and assigns it to the DurationMs field.
func (o *TaskBreakdown) SetDurationMs(v int32) {
	o.DurationMs = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *TaskBreakdown) GetEvents() []AgentEvent {
	if o == nil || IsNil(o.Events) {
		var ret []AgentEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetEventsOk() ([]AgentEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *TaskBreakdown) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []AgentEvent and assigns it to the Events field.
func (o *TaskBreakdown) SetEvents(v []AgentEvent) {
	o.Events = v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *TaskBreakdown) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *TaskBreakdown) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *TaskBreakdown) SetIndex(v int32) {
	o.Index = &v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise.
func (o *TaskBreakdown) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens) {
		var ret int32
		return ret
	}
	return *o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.InputTokens) {
		return nil, false
	}
	return o.InputTokens, true
}

// HasInputTokens returns a boolean if a field has been set.
func (o *TaskBreakdown) HasInputTokens() bool {
	if o != nil && !IsNil(o.InputTokens) {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given int32 and assigns it to the InputTokens field.
func (o *TaskBreakdown) SetInputTokens(v int32) {
	o.InputTokens = &v
}

// GetInstruction returns the Instruction field value if set, zero value otherwise.
func (o *TaskBreakdown) GetInstruction() string {
	if o == nil || IsNil(o.Instruction) {
		var ret string
		return ret
	}
	return *o.Instruction
}

// GetInstructionOk returns a tuple with the Instruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetInstructionOk() (*string, bool) {
	if o == nil || IsNil(o.Instruction) {
		return nil, false
	}
	return o.Instruction, true
}

// HasInstruction returns a boolean if a field has been set.
func (o *TaskBreakdown) HasInstruction() bool {
	if o != nil && !IsNil(o.Instruction) {
		return true
	}

	return false
}

// SetInstruction gets a reference to the given string and assigns it to the Instruction field.
func (o *TaskBreakdown) SetInstruction(v string) {
	o.Instruction = &v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise.
func (o *TaskBreakdown) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens) {
		var ret int32
		return ret
	}
	return *o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetOutputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputTokens) {
		return nil, false
	}
	return o.OutputTokens, true
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *TaskBreakdown) HasOutputTokens() bool {
	if o != nil && !IsNil(o.OutputTokens) {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given int32 and assigns it to the OutputTokens field.
func (o *TaskBreakdown) SetOutputTokens(v int32) {
	o.OutputTokens = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *TaskBreakdown) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt) {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetStartedAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *TaskBreakdown) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *TaskBreakdown) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetSteer returns the Steer field value if set, zero value otherwise.
func (o *TaskBreakdown) GetSteer() bool {
	if o == nil || IsNil(o.Steer) {
		var ret bool
		return ret
	}
	return *o.Steer
}

// GetSteerOk returns a tuple with the Steer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetSteerOk() (*bool, bool) {
	if o == nil || IsNil(o.Steer) {
		return nil, false
	}
	return o.Steer, true
}

// HasSteer returns a boolean if a field has been set.
func (o *TaskBreakdown) HasSteer() bool {
	if o != nil && !IsNil(o.Steer) {
		return true
	}

	return false
}

// SetSteer gets a reference to the given bool and assigns it to the Steer field.
func (o *TaskBreakdown) SetSteer(v bool) {
	o.Steer = &v
}

// GetTurns returns the Turns field value if set, zero value otherwise.
func (o *TaskBreakdown) GetTurns() int32 {
	if o == nil || IsNil(o.Turns) {
		var ret int32
		return ret
	}
	return *o.Turns
}

// GetTurnsOk returns a tuple with the Turns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskBreakdown) GetTurnsOk() (*int32, bool) {
	if o == nil || IsNil(o.Turns) {
		return nil, false
	}
	return o.Turns, true
}

// HasTurns returns a boolean if a field has been set.
func (o *TaskBreakdown) HasTurns() bool {
	if o != nil && !IsNil(o.Turns) {
		return true
	}

	return false
}

// SetTurns gets a reference to the given int32 and assigns it to the Turns field.
func (o *TaskBreakdown) SetTurns(v int32) {
	o.Turns = &v
}

func (o TaskBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CacheCreateTokens) {
		toSerialize["cacheCreateTokens"] = o.CacheCreateTokens
	}
	if !IsNil(o.CacheReadTokens) {
		toSerialize["cacheReadTokens"] = o.CacheReadTokens
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completedAt"] = o.CompletedAt
	}
	if !IsNil(o.CostUSD) {
		toSerialize["costUSD"] = o.CostUSD
	}
	if !IsNil(o.DurationMs) {
		toSerialize["durationMs"] = o.DurationMs
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.InputTokens) {
		toSerialize["inputTokens"] = o.InputTokens
	}
	if !IsNil(o.Instruction) {
		toSerialize["instruction"] = o.Instruction
	}
	if !IsNil(o.OutputTokens) {
		toSerialize["outputTokens"] = o.OutputTokens
	}
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.Steer) {
		toSerialize["steer"] = o.Steer
	}
	if !IsNil(o.Turns) {
		toSerialize["turns"] = o.Turns
	}
	return toSerialize, nil
}

type NullableTaskBreakdown struct {
	value *TaskBreakdown
	isSet bool
}

func (v NullableTaskBreakdown) Get() *TaskBreakdown {
	return v.value
}

func (v *NullableTaskBreakdown) Set(val *TaskBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskBreakdown(val *TaskBreakdown) *NullableTaskBreakdown {
	return &NullableTaskBreakdown{value: val, isSet: true}
}

func (v NullableTaskBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


