/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSquadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSquadRequest{}

// CreateSquadRequest struct for CreateSquadRequest
type CreateSquadRequest struct {
	Members []V1alpha1KomputerSquadMember `json:"members"`
	Name string `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
	// duration string e.g. \"10m\"
	OrphanTTL *string `json:"orphanTTL,omitempty"`
}

type _CreateSquadRequest CreateSquadRequest

// NewCreateSquadRequest instantiates a new CreateSquadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSquadRequest(members []V1alpha1KomputerSquadMember, name string) *CreateSquadRequest {
	this := CreateSquadRequest{}
	this.Members = members
	this.Name = name
	return &this
}

// NewCreateSquadRequestWithDefaults instantiates a new CreateSquadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSquadRequestWithDefaults() *CreateSquadRequest {
	this := CreateSquadRequest{}
	return &this
}

// GetMembers returns the Members field value
func (o *CreateSquadRequest) GetMembers() []V1alpha1KomputerSquadMember {
	if o == nil {
		var ret []V1alpha1KomputerSquadMember
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *CreateSquadRequest) GetMembersOk() ([]V1alpha1KomputerSquadMember, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *CreateSquadRequest) SetMembers(v []V1alpha1KomputerSquadMember) {
	o.Members = v
}

// GetName returns the Name field value
func (o *CreateSquadRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSquadRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSquadRequest) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *CreateSquadRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSquadRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *CreateSquadRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *CreateSquadRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOrphanTTL returns the OrphanTTL field value if set, zero value otherwise.
func (o *CreateSquadRequest) GetOrphanTTL() string {
	if o == nil || IsNil(o.OrphanTTL) {
		var ret string
		return ret
	}
	return *o.OrphanTTL
}

// GetOrphanTTLOk returns a tuple with the OrphanTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSquadRequest) GetOrphanTTLOk() (*string, bool) {
	if o == nil || IsNil(o.OrphanTTL) {
		return nil, false
	}
	return o.OrphanTTL, true
}

// HasOrphanTTL returns a boolean if a field has been set.
func (o *CreateSquadRequest) HasOrphanTTL() bool {
	if o != nil && !IsNil(o.OrphanTTL) {
		return true
	}

	return false
}

// SetOrphanTTL gets a reference to the given string and assigns it to the OrphanTTL field.
func (o *CreateSquadRequest) SetOrphanTTL(v string) {
	o.OrphanTTL = &v
}

func (o CreateSquadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSquadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["members"] = o.Members
	toSerialize["name"] = o.Name
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.OrphanTTL) {
		toSerialize["orphanTTL"] = o.OrphanTTL
	}
	return toSerialize, nil
}

func (o *CreateSquadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"members",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSquadRequest := _CreateSquadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSquadRequest)

	if err != nil {
		return err
	}

	*o = CreateSquadRequest(varCreateSquadRequest)

	return err
}

type NullableCreateSquadRequest struct {
	value *CreateSquadRequest
	isSet bool
}

func (v NullableCreateSquadRequest) Get() *CreateSquadRequest {
	return v.value
}

func (v *NullableCreateSquadRequest) Set(val *CreateSquadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSquadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSquadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSquadRequest(val *CreateSquadRequest) *NullableCreateSquadRequest {
	return &NullableCreateSquadRequest{value: val, isSet: true}
}

func (v NullableCreateSquadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSquadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


