/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the UpdateConnectorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConnectorRequest{}

// UpdateConnectorRequest struct for UpdateConnectorRequest
type UpdateConnectorRequest struct {
	// Disabled toggles whether the connector can be newly attached to agents and whether its tools are resolved for agent pods. true disables, false re-enables. Any caller may toggle this — there is no additional authorization check.
	Disabled *bool `json:"disabled,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	// new auth token; replaces the value in the connector's secret
	Token *string `json:"token,omitempty"`
}

// NewUpdateConnectorRequest instantiates a new UpdateConnectorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConnectorRequest() *UpdateConnectorRequest {
	this := UpdateConnectorRequest{}
	return &this
}

// NewUpdateConnectorRequestWithDefaults instantiates a new UpdateConnectorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConnectorRequestWithDefaults() *UpdateConnectorRequest {
	this := UpdateConnectorRequest{}
	return &this
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *UpdateConnectorRequest) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorRequest) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *UpdateConnectorRequest) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *UpdateConnectorRequest) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *UpdateConnectorRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *UpdateConnectorRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *UpdateConnectorRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UpdateConnectorRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UpdateConnectorRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UpdateConnectorRequest) SetToken(v string) {
	o.Token = &v
}

func (o UpdateConnectorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConnectorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableUpdateConnectorRequest struct {
	value *UpdateConnectorRequest
	isSet bool
}

func (v NullableUpdateConnectorRequest) Get() *UpdateConnectorRequest {
	return v.value
}

func (v *NullableUpdateConnectorRequest) Set(val *UpdateConnectorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConnectorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConnectorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConnectorRequest(val *UpdateConnectorRequest) *NullableUpdateConnectorRequest {
	return &NullableUpdateConnectorRequest{value: val, isSet: true}
}

func (v NullableUpdateConnectorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConnectorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


