/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1alpha1AgentLifecycle the model 'V1alpha1AgentLifecycle'
type V1alpha1AgentLifecycle string

// List of v1alpha1.AgentLifecycle
const (
	AgentLifecycleDefault V1alpha1AgentLifecycle = ""
	AgentLifecycleSleep V1alpha1AgentLifecycle = "Sleep"
	AgentLifecycleAutoDelete V1alpha1AgentLifecycle = "AutoDelete"
)

// All allowed values of V1alpha1AgentLifecycle enum
var AllowedV1alpha1AgentLifecycleEnumValues = []V1alpha1AgentLifecycle{
	"",
	"Sleep",
	"AutoDelete",
}

func (v *V1alpha1AgentLifecycle) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1alpha1AgentLifecycle(value)
	for _, existing := range AllowedV1alpha1AgentLifecycleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1alpha1AgentLifecycle", value)
}

// NewV1alpha1AgentLifecycleFromValue returns a pointer to a valid V1alpha1AgentLifecycle
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1alpha1AgentLifecycleFromValue(v string) (*V1alpha1AgentLifecycle, error) {
	ev := V1alpha1AgentLifecycle(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1alpha1AgentLifecycle: valid values are %v", v, AllowedV1alpha1AgentLifecycleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1alpha1AgentLifecycle) IsValid() bool {
	for _, existing := range AllowedV1alpha1AgentLifecycleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1alpha1.AgentLifecycle value
func (v V1alpha1AgentLifecycle) Ptr() *V1alpha1AgentLifecycle {
	return &v
}

type NullableV1alpha1AgentLifecycle struct {
	value *V1alpha1AgentLifecycle
	isSet bool
}

func (v NullableV1alpha1AgentLifecycle) Get() *V1alpha1AgentLifecycle {
	return v.value
}

func (v *NullableV1alpha1AgentLifecycle) Set(val *V1alpha1AgentLifecycle) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1AgentLifecycle) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1AgentLifecycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1AgentLifecycle(val *V1alpha1AgentLifecycle) *NullableV1alpha1AgentLifecycle {
	return &NullableV1alpha1AgentLifecycle{value: val, isSet: true}
}

func (v NullableV1alpha1AgentLifecycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1AgentLifecycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

