/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the V1alpha1KomputerSquadMemberRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1KomputerSquadMemberRef{}

// V1alpha1KomputerSquadMemberRef struct for V1alpha1KomputerSquadMemberRef
type V1alpha1KomputerSquadMemberRef struct {
	Name *string `json:"name,omitempty"`
	// defaults to squad's namespace
	Namespace *string `json:"namespace,omitempty"`
}

// NewV1alpha1KomputerSquadMemberRef instantiates a new V1alpha1KomputerSquadMemberRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1KomputerSquadMemberRef() *V1alpha1KomputerSquadMemberRef {
	this := V1alpha1KomputerSquadMemberRef{}
	return &this
}

// NewV1alpha1KomputerSquadMemberRefWithDefaults instantiates a new V1alpha1KomputerSquadMemberRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1KomputerSquadMemberRefWithDefaults() *V1alpha1KomputerSquadMemberRef {
	this := V1alpha1KomputerSquadMemberRef{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1alpha1KomputerSquadMemberRef) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1KomputerSquadMemberRef) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1alpha1KomputerSquadMemberRef) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1alpha1KomputerSquadMemberRef) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *V1alpha1KomputerSquadMemberRef) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1KomputerSquadMemberRef) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *V1alpha1KomputerSquadMemberRef) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *V1alpha1KomputerSquadMemberRef) SetNamespace(v string) {
	o.Namespace = &v
}

func (o V1alpha1KomputerSquadMemberRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1KomputerSquadMemberRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return toSerialize, nil
}

type NullableV1alpha1KomputerSquadMemberRef struct {
	value *V1alpha1KomputerSquadMemberRef
	isSet bool
}

func (v NullableV1alpha1KomputerSquadMemberRef) Get() *V1alpha1KomputerSquadMemberRef {
	return v.value
}

func (v *NullableV1alpha1KomputerSquadMemberRef) Set(val *V1alpha1KomputerSquadMemberRef) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1KomputerSquadMemberRef) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1KomputerSquadMemberRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1KomputerSquadMemberRef(val *V1alpha1KomputerSquadMemberRef) *NullableV1alpha1KomputerSquadMemberRef {
	return &NullableV1alpha1KomputerSquadMemberRef{value: val, isSet: true}
}

func (v NullableV1alpha1KomputerSquadMemberRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1KomputerSquadMemberRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


