/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the SquadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SquadResponse{}

// SquadResponse struct for SquadResponse
type SquadResponse struct {
	BreakUpRequested *bool `json:"breakUpRequested,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	Members []SquadMemberResponse `json:"members,omitempty"`
	Message *string `json:"message,omitempty"`
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	OrphanTTL *string `json:"orphanTTL,omitempty"`
	OrphanedSince *string `json:"orphanedSince,omitempty"`
	Phase *string `json:"phase,omitempty"`
	PodName *string `json:"podName,omitempty"`
}

// NewSquadResponse instantiates a new SquadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSquadResponse() *SquadResponse {
	this := SquadResponse{}
	return &this
}

// NewSquadResponseWithDefaults instantiates a new SquadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSquadResponseWithDefaults() *SquadResponse {
	this := SquadResponse{}
	return &this
}

// GetBreakUpRequested returns the BreakUpRequested field value if set, zero value otherwise.
func (o *SquadResponse) GetBreakUpRequested() bool {
	if o == nil || IsNil(o.BreakUpRequested) {
		var ret bool
		return ret
	}
	return *o.BreakUpRequested
}

// GetBreakUpRequestedOk returns a tuple with the BreakUpRequested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetBreakUpRequestedOk() (*bool, bool) {
	if o == nil || IsNil(o.BreakUpRequested) {
		return nil, false
	}
	return o.BreakUpRequested, true
}

// HasBreakUpRequested returns a boolean if a field has been set.
func (o *SquadResponse) HasBreakUpRequested() bool {
	if o != nil && !IsNil(o.BreakUpRequested) {
		return true
	}

	return false
}

// SetBreakUpRequested gets a reference to the given bool and assigns it to the BreakUpRequested field.
func (o *SquadResponse) SetBreakUpRequested(v bool) {
	o.BreakUpRequested = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SquadResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SquadResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SquadResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *SquadResponse) GetMembers() []SquadMemberResponse {
	if o == nil || IsNil(o.Members) {
		var ret []SquadMemberResponse
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetMembersOk() ([]SquadMemberResponse, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *SquadResponse) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []SquadMemberResponse and assigns it to the Members field.
func (o *SquadResponse) SetMembers(v []SquadMemberResponse) {
	o.Members = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SquadResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SquadResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SquadResponse) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SquadResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SquadResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SquadResponse) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *SquadResponse) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *SquadResponse) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *SquadResponse) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOrphanTTL returns the OrphanTTL field value if set, zero value otherwise.
func (o *SquadResponse) GetOrphanTTL() string {
	if o == nil || IsNil(o.OrphanTTL) {
		var ret string
		return ret
	}
	return *o.OrphanTTL
}

// GetOrphanTTLOk returns a tuple with the OrphanTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetOrphanTTLOk() (*string, bool) {
	if o == nil || IsNil(o.OrphanTTL) {
		return nil, false
	}
	return o.OrphanTTL, true
}

// HasOrphanTTL returns a boolean if a field has been set.
func (o *SquadResponse) HasOrphanTTL() bool {
	if o != nil && !IsNil(o.OrphanTTL) {
		return true
	}

	return false
}

// SetOrphanTTL gets a reference to the given string and assigns it to the OrphanTTL field.
func (o *SquadResponse) SetOrphanTTL(v string) {
	o.OrphanTTL = &v
}

// GetOrphanedSince returns the OrphanedSince field value if set, zero value otherwise.
func (o *SquadResponse) GetOrphanedSince() string {
	if o == nil || IsNil(o.OrphanedSince) {
		var ret string
		return ret
	}
	return *o.OrphanedSince
}

// GetOrphanedSinceOk returns a tuple with the OrphanedSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetOrphanedSinceOk() (*string, bool) {
	if o == nil || IsNil(o.OrphanedSince) {
		return nil, false
	}
	return o.OrphanedSince, true
}

// HasOrphanedSince returns a boolean if a field has been set.
func (o *SquadResponse) HasOrphanedSince() bool {
	if o != nil && !IsNil(o.OrphanedSince) {
		return true
	}

	return false
}

// SetOrphanedSince gets a reference to the given string and assigns it to the OrphanedSince field.
func (o *SquadResponse) SetOrphanedSince(v string) {
	o.OrphanedSince = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *SquadResponse) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *SquadResponse) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *SquadResponse) SetPhase(v string) {
	o.Phase = &v
}

// GetPodName returns the PodName field value if set, zero value otherwise.
func (o *SquadResponse) GetPodName() string {
	if o == nil || IsNil(o.PodName) {
		var ret string
		return ret
	}
	return *o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SquadResponse) GetPodNameOk() (*string, bool) {
	if o == nil || IsNil(o.PodName) {
		return nil, false
	}
	return o.PodName, true
}

// HasPodName returns a boolean if a field has been set.
func (o *SquadResponse) HasPodName() bool {
	if o != nil && !IsNil(o.PodName) {
		return true
	}

	return false
}

// SetPodName gets a reference to the given string and assigns it to the PodName field.
func (o *SquadResponse) SetPodName(v string) {
	o.PodName = &v
}

func (o SquadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SquadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BreakUpRequested) {
		toSerialize["breakUpRequested"] = o.BreakUpRequested
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.OrphanTTL) {
		toSerialize["orphanTTL"] = o.OrphanTTL
	}
	if !IsNil(o.OrphanedSince) {
		toSerialize["orphanedSince"] = o.OrphanedSince
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.PodName) {
		toSerialize["podName"] = o.PodName
	}
	return toSerialize, nil
}

type NullableSquadResponse struct {
	value *SquadResponse
	isSet bool
}

func (v NullableSquadResponse) Get() *SquadResponse {
	return v.value
}

func (v *NullableSquadResponse) Set(val *SquadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSquadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSquadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSquadResponse(val *SquadResponse) *NullableSquadResponse {
	return &NullableSquadResponse{value: val, isSet: true}
}

func (v NullableSquadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSquadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


