/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the V1alpha1KomputerSquadMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1KomputerSquadMember{}

// V1alpha1KomputerSquadMember struct for V1alpha1KomputerSquadMember
type V1alpha1KomputerSquadMember struct {
	// Exactly one of Ref or Spec must be set.
	Ref *V1alpha1KomputerSquadMemberRef `json:"ref,omitempty"`
	Spec *V1alpha1KomputerAgentSpec `json:"spec,omitempty"`
}

// NewV1alpha1KomputerSquadMember instantiates a new V1alpha1KomputerSquadMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1KomputerSquadMember() *V1alpha1KomputerSquadMember {
	this := V1alpha1KomputerSquadMember{}
	return &this
}

// NewV1alpha1KomputerSquadMemberWithDefaults instantiates a new V1alpha1KomputerSquadMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1KomputerSquadMemberWithDefaults() *V1alpha1KomputerSquadMember {
	this := V1alpha1KomputerSquadMember{}
	return &this
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *V1alpha1KomputerSquadMember) GetRef() V1alpha1KomputerSquadMemberRef {
	if o == nil || IsNil(o.Ref) {
		var ret V1alpha1KomputerSquadMemberRef
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1KomputerSquadMember) GetRefOk() (*V1alpha1KomputerSquadMemberRef, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *V1alpha1KomputerSquadMember) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given V1alpha1KomputerSquadMemberRef and assigns it to the Ref field.
func (o *V1alpha1KomputerSquadMember) SetRef(v V1alpha1KomputerSquadMemberRef) {
	o.Ref = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *V1alpha1KomputerSquadMember) GetSpec() V1alpha1KomputerAgentSpec {
	if o == nil || IsNil(o.Spec) {
		var ret V1alpha1KomputerAgentSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1KomputerSquadMember) GetSpecOk() (*V1alpha1KomputerAgentSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *V1alpha1KomputerSquadMember) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given V1alpha1KomputerAgentSpec and assigns it to the Spec field.
func (o *V1alpha1KomputerSquadMember) SetSpec(v V1alpha1KomputerAgentSpec) {
	o.Spec = &v
}

func (o V1alpha1KomputerSquadMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1KomputerSquadMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableV1alpha1KomputerSquadMember struct {
	value *V1alpha1KomputerSquadMember
	isSet bool
}

func (v NullableV1alpha1KomputerSquadMember) Get() *V1alpha1KomputerSquadMember {
	return v.value
}

func (v *NullableV1alpha1KomputerSquadMember) Set(val *V1alpha1KomputerSquadMember) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1KomputerSquadMember) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1KomputerSquadMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1KomputerSquadMember(val *V1alpha1KomputerSquadMember) *NullableV1alpha1KomputerSquadMember {
	return &NullableV1alpha1KomputerSquadMember{value: val, isSet: true}
}

func (v NullableV1alpha1KomputerSquadMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1KomputerSquadMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


