/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the PatchSquadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchSquadRequest{}

// PatchSquadRequest struct for PatchSquadRequest
type PatchSquadRequest struct {
	Members []V1alpha1KomputerSquadMember `json:"members,omitempty"`
	OrphanTTL *string `json:"orphanTTL,omitempty"`
}

// NewPatchSquadRequest instantiates a new PatchSquadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchSquadRequest() *PatchSquadRequest {
	this := PatchSquadRequest{}
	return &this
}

// NewPatchSquadRequestWithDefaults instantiates a new PatchSquadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchSquadRequestWithDefaults() *PatchSquadRequest {
	this := PatchSquadRequest{}
	return &this
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *PatchSquadRequest) GetMembers() []V1alpha1KomputerSquadMember {
	if o == nil || IsNil(o.Members) {
		var ret []V1alpha1KomputerSquadMember
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSquadRequest) GetMembersOk() ([]V1alpha1KomputerSquadMember, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *PatchSquadRequest) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []V1alpha1KomputerSquadMember and assigns it to the Members field.
func (o *PatchSquadRequest) SetMembers(v []V1alpha1KomputerSquadMember) {
	o.Members = v
}

// GetOrphanTTL returns the OrphanTTL field value if set, zero value otherwise.
func (o *PatchSquadRequest) GetOrphanTTL() string {
	if o == nil || IsNil(o.OrphanTTL) {
		var ret string
		return ret
	}
	return *o.OrphanTTL
}

// GetOrphanTTLOk returns a tuple with the OrphanTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSquadRequest) GetOrphanTTLOk() (*string, bool) {
	if o == nil || IsNil(o.OrphanTTL) {
		return nil, false
	}
	return o.OrphanTTL, true
}

// HasOrphanTTL returns a boolean if a field has been set.
func (o *PatchSquadRequest) HasOrphanTTL() bool {
	if o != nil && !IsNil(o.OrphanTTL) {
		return true
	}

	return false
}

// SetOrphanTTL gets a reference to the given string and assigns it to the OrphanTTL field.
func (o *PatchSquadRequest) SetOrphanTTL(v string) {
	o.OrphanTTL = &v
}

func (o PatchSquadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchSquadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.OrphanTTL) {
		toSerialize["orphanTTL"] = o.OrphanTTL
	}
	return toSerialize, nil
}

type NullablePatchSquadRequest struct {
	value *PatchSquadRequest
	isSet bool
}

func (v NullablePatchSquadRequest) Get() *PatchSquadRequest {
	return v.value
}

func (v *NullablePatchSquadRequest) Set(val *PatchSquadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchSquadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchSquadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchSquadRequest(val *PatchSquadRequest) *NullablePatchSquadRequest {
	return &NullablePatchSquadRequest{value: val, isSet: true}
}

func (v NullablePatchSquadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchSquadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


