/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the V1Duration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1Duration{}

// V1Duration struct for V1Duration
type V1Duration struct {
	TimeDuration *int64 `json:"time.Duration,omitempty"`
}

// NewV1Duration instantiates a new V1Duration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Duration() *V1Duration {
	this := V1Duration{}
	return &this
}

// NewV1DurationWithDefaults instantiates a new V1Duration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DurationWithDefaults() *V1Duration {
	this := V1Duration{}
	return &this
}

// GetTimeDuration returns the TimeDuration field value if set, zero value otherwise.
func (o *V1Duration) GetTimeDuration() int64 {
	if o == nil || IsNil(o.TimeDuration) {
		var ret int64
		return ret
	}
	return *o.TimeDuration
}

// GetTimeDurationOk returns a tuple with the TimeDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Duration) GetTimeDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeDuration) {
		return nil, false
	}
	return o.TimeDuration, true
}

// HasTimeDuration returns a boolean if a field has been set.
func (o *V1Duration) HasTimeDuration() bool {
	if o != nil && !IsNil(o.TimeDuration) {
		return true
	}

	return false
}

// SetTimeDuration gets a reference to the given int64 and assigns it to the TimeDuration field.
func (o *V1Duration) SetTimeDuration(v int64) {
	o.TimeDuration = &v
}

func (o V1Duration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1Duration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeDuration) {
		toSerialize["time.Duration"] = o.TimeDuration
	}
	return toSerialize, nil
}

type NullableV1Duration struct {
	value *V1Duration
	isSet bool
}

func (v NullableV1Duration) Get() *V1Duration {
	return v.value
}

func (v *NullableV1Duration) Set(val *V1Duration) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Duration) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Duration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Duration(val *V1Duration) *NullableV1Duration {
	return &NullableV1Duration{value: val, isSet: true}
}

func (v NullableV1Duration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Duration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


