apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/finalizers
  verbs:
  - update
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragentclustertemplates
  - komputeragenttemplates
  - komputerconfigs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
