apiVersion: komputer.komputer.ai/v1alpha1
kind: KomputerRedisConfig
metadata:
  name: default
spec:
  address: "redis.default:6379"
  db: 0
  queue: "komputer-events"
  passwordSecret:
    name: "redis-secret"
    key: "password"
