/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddSquadMemberRequest,
  CreateSquadRequest,
  PatchSquadRequest,
  SquadListResponse,
  SquadResponse,
} from '../models/index';
import {
    AddSquadMemberRequestFromJSON,
    AddSquadMemberRequestToJSON,
    CreateSquadRequestFromJSON,
    CreateSquadRequestToJSON,
    PatchSquadRequestFromJSON,
    PatchSquadRequestToJSON,
    SquadListResponseFromJSON,
    SquadListResponseToJSON,
    SquadResponseFromJSON,
    SquadResponseToJSON,
} from '../models/index';

export interface AddSquadMemberOperationRequest {
    name: string;
    request: AddSquadMemberRequest;
    namespace?: string;
}

export interface BreakUpSquadRequest {
    name: string;
    namespace?: string;
}

export interface DeleteSquadRequest {
    name: string;
    namespace?: string;
}

export interface GetSquadRequest {
    name: string;
    namespace?: string;
}

export interface ListSquadsRequest {
    namespace?: string;
}

export interface PatchSquadOperationRequest {
    name: string;
    request: PatchSquadRequest;
    namespace?: string;
}

export interface RemoveSquadMemberRequest {
    name: string;
    agent: string;
    namespace?: string;
}

export interface SquadsPostRequest {
    request: CreateSquadRequest;
}

/**
 * 
 */
export class SquadsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addSquadMember without sending the request
     */
    async addSquadMemberRequestOpts(requestParameters: AddSquadMemberOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling addSquadMember().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling addSquadMember().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/squads/{name}/members`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddSquadMemberRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Appends a member (by ref or inline spec) to the squad\'s member list.
     * Add squad member
     */
    async addSquadMemberRaw(requestParameters: AddSquadMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.addSquadMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     * Appends a member (by ref or inline spec) to the squad\'s member list.
     * Add squad member
     */
    async addSquadMember(requestParameters: AddSquadMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.addSquadMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for breakUpSquad without sending the request
     */
    async breakUpSquadRequestOpts(requestParameters: BreakUpSquadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling breakUpSquad().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/squads/{name}/break-up`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks the squad for dissolution once all members are asleep.
     * Request squad break-up
     */
    async breakUpSquadRaw(requestParameters: BreakUpSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.breakUpSquadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     * Marks the squad for dissolution once all members are asleep.
     * Request squad break-up
     */
    async breakUpSquad(requestParameters: BreakUpSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.breakUpSquadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSquad without sending the request
     */
    async deleteSquadRequestOpts(requestParameters: DeleteSquadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteSquad().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/squads/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the squad CR. The operator will clean up the shared pod.
     * Delete squad
     */
    async deleteSquadRaw(requestParameters: DeleteSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.deleteSquadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes the squad CR. The operator will clean up the shared pod.
     * Delete squad
     */
    async deleteSquad(requestParameters: DeleteSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.deleteSquadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSquad without sending the request
     */
    async getSquadRequestOpts(requestParameters: GetSquadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getSquad().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/squads/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current status and member list for a single squad.
     * Get squad details
     */
    async getSquadRaw(requestParameters: GetSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.getSquadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current status and member list for a single squad.
     * Get squad details
     */
    async getSquad(requestParameters: GetSquadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.getSquadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSquads without sending the request
     */
    async listSquadsRequestOpts(requestParameters: ListSquadsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/squads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all squads with their current status. Pass ?namespace= to filter; omit for all namespaces.
     * List squads
     */
    async listSquadsRaw(requestParameters: ListSquadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadListResponse>> {
        const requestOptions = await this.listSquadsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all squads with their current status. Pass ?namespace= to filter; omit for all namespaces.
     * List squads
     */
    async listSquads(requestParameters: ListSquadsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadListResponse> {
        const response = await this.listSquadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchSquad without sending the request
     */
    async patchSquadRequestOpts(requestParameters: PatchSquadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling patchSquad().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling patchSquad().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/squads/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchSquadRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Replaces the member list and/or orphanTTL on an existing squad. Retries once on 409 conflict.
     * Patch squad
     */
    async patchSquadRaw(requestParameters: PatchSquadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.patchSquadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the member list and/or orphanTTL on an existing squad. Retries once on 409 conflict.
     * Patch squad
     */
    async patchSquad(requestParameters: PatchSquadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.patchSquadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeSquadMember without sending the request
     */
    async removeSquadMemberRequestOpts(requestParameters: RemoveSquadMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling removeSquadMember().'
            );
        }

        if (requestParameters['agent'] == null) {
            throw new runtime.RequiredError(
                'agent',
                'Required parameter "agent" was null or undefined when calling removeSquadMember().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/squads/{name}/members/{agent}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace(`{${"agent"}}`, encodeURIComponent(String(requestParameters['agent'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the named member from the squad\'s member list (matched by ref.name or spec-based name).
     * Remove squad member
     */
    async removeSquadMemberRaw(requestParameters: RemoveSquadMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.removeSquadMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     * Removes the named member from the squad\'s member list (matched by ref.name or spec-based name).
     * Remove squad member
     */
    async removeSquadMember(requestParameters: RemoveSquadMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.removeSquadMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for squadsPost without sending the request
     */
    async squadsPostRequestOpts(requestParameters: SquadsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling squadsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/squads`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSquadRequestToJSON(requestParameters['request']),
        };
    }

    /**
     */
    async squadsPostRaw(requestParameters: SquadsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SquadResponse>> {
        const requestOptions = await this.squadsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SquadResponseFromJSON(jsonValue));
    }

    /**
     */
    async squadsPost(requestParameters: SquadsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SquadResponse> {
        const response = await this.squadsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
