{{- if .Values.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end }}
