# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from komputer_ai.models.agent_event import AgentEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TaskBreakdown(BaseModel):
    """
    TaskBreakdown
    """ # noqa: E501
    cache_create_tokens: Optional[StrictInt] = Field(default=None, alias="cacheCreateTokens")
    cache_read_tokens: Optional[StrictInt] = Field(default=None, alias="cacheReadTokens")
    completed_at: Optional[StrictStr] = Field(default=None, alias="completedAt")
    cost_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="costUSD")
    duration_ms: Optional[StrictInt] = Field(default=None, alias="durationMs")
    events: Optional[List[AgentEvent]] = None
    index: Optional[StrictInt] = None
    input_tokens: Optional[StrictInt] = Field(default=None, alias="inputTokens")
    instruction: Optional[StrictStr] = None
    output_tokens: Optional[StrictInt] = Field(default=None, alias="outputTokens")
    started_at: Optional[StrictStr] = Field(default=None, alias="startedAt")
    steer: Optional[StrictBool] = None
    turns: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["cacheCreateTokens", "cacheReadTokens", "completedAt", "costUSD", "durationMs", "events", "index", "inputTokens", "instruction", "outputTokens", "startedAt", "steer", "turns"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cacheCreateTokens": obj.get("cacheCreateTokens"),
            "cacheReadTokens": obj.get("cacheReadTokens"),
            "completedAt": obj.get("completedAt"),
            "costUSD": obj.get("costUSD"),
            "durationMs": obj.get("durationMs"),
            "events": [AgentEvent.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "index": obj.get("index"),
            "inputTokens": obj.get("inputTokens"),
            "instruction": obj.get("instruction"),
            "outputTokens": obj.get("outputTokens"),
            "startedAt": obj.get("startedAt"),
            "steer": obj.get("steer"),
            "turns": obj.get("turns")
        })
        return _obj


