# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from komputer_ai.models.v1_duration import V1Duration
from komputer_ai.models.v1_pod_spec import V1PodSpec
from komputer_ai.models.v1alpha1_agent_lifecycle import V1alpha1AgentLifecycle
from komputer_ai.models.v1alpha1_storage_spec import V1alpha1StorageSpec
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1alpha1KomputerAgentSpec(BaseModel):
    """
    V1alpha1KomputerAgentSpec
    """ # noqa: E501
    allowed_tools: Optional[List[StrictStr]] = Field(default=None, description="AllowedTools restricts the agent to exactly these tools. When empty, the default built-in tool set is used and all tools from attached connectors are permitted.  Setting this REPLACES the default set rather than extending it, so an agent given only [\"Read\"] loses Bash, Write, Edit and the rest. Connector tools are not auto-added either — list them explicitly, e.g. \"mcp__figma__*\" for a whole connector or \"mcp__figma__get_design_context\" for a single tool. +optional", alias="allowedTools")
    connectors: Optional[List[StrictStr]] = Field(default=None, description="Connectors is a list of KomputerConnector names to attach to this agent. Names can be \"name\" (same namespace) or \"namespace/name\" (cross-namespace). +optional")
    delete_ttl: Optional[V1Duration] = Field(default=None, description="DeleteTTL deletes the entire agent (pod + PVC) once this long has elapsed since metadata.creationTimestamp. This is an absolute lifetime cap: unlike SleepTTL it does not reset on wake and applies in every phase, including Sleeping. Unset (default) means the agent never auto-deletes. Overrides the template's deleteTTL when set. +optional", alias="deleteTTL")
    disallowed_tools: Optional[List[StrictStr]] = Field(default=None, description="DisallowedTools removes these tools from the agent. Purely subtractive: the default built-ins and all connector tools remain available except what is named here. Takes precedence over AllowedTools. Supports wildcards, e.g. \"mcp__figma__*\". +optional", alias="disallowedTools")
    instructions: Optional[StrictStr] = Field(default=None, description="Instructions is the user's task for the Claude agent.")
    internal_system_prompt: Optional[StrictStr] = Field(default=None, description="InternalSystemPrompt is the built-in system prompt set by the API (role prompt + memories). +optional", alias="internalSystemPrompt")
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="Labels are user-defined key=value labels attached to this agent and propagated to all child resources (Pod, PVC, ConfigMap, Service). Keys starting with \"komputer.ai/\" are reserved for system labels and should not be set directly through the API. +optional")
    lifecycle: Optional[V1alpha1AgentLifecycle] = Field(default=None, description="Lifecycle controls what happens after task completion. Empty (default) keeps the pod running, \"Sleep\" deletes the pod but keeps the PVC, \"AutoDelete\" deletes the entire agent after task completion. +kubebuilder:validation:Enum=\"\";Sleep;AutoDelete +optional")
    memories: Optional[List[StrictStr]] = Field(default=None, description="Memories is a list of KomputerMemory names to attach to this agent. Names can be \"name\" (same namespace) or \"namespace/name\" (cross-namespace). +optional")
    model: Optional[StrictStr] = Field(default=None, description="Model is the Claude model to use. +kubebuilder:default=\"claude-sonnet-4-6\"")
    office_manager: Optional[StrictStr] = Field(default=None, description="OfficeManager is the name of the manager agent that created this sub-agent. When set, the operator creates/joins a KomputerOffice for the group. +optional", alias="officeManager")
    pod_spec: Optional[V1PodSpec] = Field(default=None, description="PodSpec, when set, overrides the template's PodSpec for this agent. Container fields are merged by name; non-zero fields from this PodSpec override the template's container fields. Takes effect on next pod start (existing pods are not mutated). +optional", alias="podSpec")
    priority: Optional[StrictInt] = Field(default=None, description="Priority controls admission order when the template's maxConcurrentAgents limit is reached. Higher number = admitted first (matches K8s PodPriority). Ties broken by creationTimestamp (older first). Defaults to 0. +kubebuilder:default=0 +optional")
    role: Optional[StrictStr] = Field(default=None, description="Role is \"manager\" or \"worker\". Managers get orchestration tools. Role is \"manager\" or \"worker\". Defaults to \"manager\" for top-level agents. Sub-agents created by managers are explicitly set to \"worker\". +kubebuilder:default=\"manager\" +kubebuilder:validation:Enum=worker;manager +optional")
    secrets: Optional[List[StrictStr]] = Field(default=None, description="Secrets is a list of K8s Secret names containing agent-specific secrets. Each key in each secret is injected as an env var into the agent pod. +optional")
    skills: Optional[List[StrictStr]] = Field(default=None, description="Skills is a list of KomputerSkill names to attach to this agent. Names can be \"name\" (same namespace) or \"namespace/name\" (cross-namespace). +optional")
    sleep_ttl: Optional[V1Duration] = Field(default=None, description="SleepTTL puts the agent to sleep (pod deleted, PVC preserved) once it has been idle for this long. Idle is measured from Status.LastActivityAt, so the clock only starts once a task has actually started, and any later task event or wake resets it. Never fires while a task is in progress, and an agent that has never run a task is never auto-slept (use DeleteTTL to reclaim those). Unset (default) means the agent never auto-sleeps. Overrides the template's sleepTTL when set. +optional", alias="sleepTTL")
    storage: Optional[V1alpha1StorageSpec] = Field(default=None, description="Storage, when set, overrides the template's storage settings for this agent. Existing PVCs are expanded in place when the storage class supports it. +optional")
    system_prompt: Optional[StrictStr] = Field(default=None, description="SystemPrompt is a custom system prompt provided by the user, appended to the internal prompt. +optional", alias="systemPrompt")
    template_ref: Optional[StrictStr] = Field(default=None, description="TemplateRef is the name of the KomputerAgentTemplate to use. +kubebuilder:default=\"default\"", alias="templateRef")
    __properties: ClassVar[List[str]] = ["allowedTools", "connectors", "deleteTTL", "disallowedTools", "instructions", "internalSystemPrompt", "labels", "lifecycle", "memories", "model", "officeManager", "podSpec", "priority", "role", "secrets", "skills", "sleepTTL", "storage", "systemPrompt", "templateRef"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1alpha1KomputerAgentSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delete_ttl
        if self.delete_ttl:
            _dict['deleteTTL'] = self.delete_ttl.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pod_spec
        if self.pod_spec:
            _dict['podSpec'] = self.pod_spec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sleep_ttl
        if self.sleep_ttl:
            _dict['sleepTTL'] = self.sleep_ttl.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage
        if self.storage:
            _dict['storage'] = self.storage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1alpha1KomputerAgentSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowedTools": obj.get("allowedTools"),
            "connectors": obj.get("connectors"),
            "deleteTTL": V1Duration.from_dict(obj["deleteTTL"]) if obj.get("deleteTTL") is not None else None,
            "disallowedTools": obj.get("disallowedTools"),
            "instructions": obj.get("instructions"),
            "internalSystemPrompt": obj.get("internalSystemPrompt"),
            "labels": obj.get("labels"),
            "lifecycle": obj.get("lifecycle"),
            "memories": obj.get("memories"),
            "model": obj.get("model"),
            "officeManager": obj.get("officeManager"),
            "podSpec": V1PodSpec.from_dict(obj["podSpec"]) if obj.get("podSpec") is not None else None,
            "priority": obj.get("priority"),
            "role": obj.get("role"),
            "secrets": obj.get("secrets"),
            "skills": obj.get("skills"),
            "sleepTTL": V1Duration.from_dict(obj["sleepTTL"]) if obj.get("sleepTTL") is not None else None,
            "storage": V1alpha1StorageSpec.from_dict(obj["storage"]) if obj.get("storage") is not None else None,
            "systemPrompt": obj.get("systemPrompt"),
            "templateRef": obj.get("templateRef")
        })
        return _obj


