/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentEvent
 */
export interface AgentEvent {
    /**
     * 
     * @type {string}
     * @memberof AgentEvent
     */
    agentName?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentEvent
     */
    namespace?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AgentEvent
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof AgentEvent
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentEvent
     */
    type?: string;
}

/**
 * Check if a given object implements the AgentEvent interface.
 */
export function instanceOfAgentEvent(value: object): value is AgentEvent {
    return true;
}

export function AgentEventFromJSON(json: any): AgentEvent {
    return AgentEventFromJSONTyped(json, false);
}

export function AgentEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'agentName': json['agentName'] == null ? undefined : json['agentName'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AgentEventToJSON(json: any): AgentEvent {
    return AgentEventToJSONTyped(json, false);
}

export function AgentEventToJSONTyped(value?: AgentEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentName': value['agentName'],
        'namespace': value['namespace'],
        'payload': value['payload'],
        'timestamp': value['timestamp'],
        'type': value['type'],
    };
}

