/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompactAgentRequest
 */
export interface CompactAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof CompactAgentRequest
     */
    instructions?: string;
}

/**
 * Check if a given object implements the CompactAgentRequest interface.
 */
export function instanceOfCompactAgentRequest(value: object): value is CompactAgentRequest {
    return true;
}

export function CompactAgentRequestFromJSON(json: any): CompactAgentRequest {
    return CompactAgentRequestFromJSONTyped(json, false);
}

export function CompactAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompactAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
    };
}

export function CompactAgentRequestToJSON(json: any): CompactAgentRequest {
    return CompactAgentRequestToJSONTyped(json, false);
}

export function CompactAgentRequestToJSONTyped(value?: CompactAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instructions': value['instructions'],
    };
}

