/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskBreakdown } from './TaskBreakdown';
import {
    TaskBreakdownFromJSON,
    TaskBreakdownFromJSONTyped,
    TaskBreakdownToJSON,
    TaskBreakdownToJSONTyped,
} from './TaskBreakdown';

/**
 * 
 * @export
 * @interface CostBreakdownResponse
 */
export interface CostBreakdownResponse {
    /**
     * 
     * @type {string}
     * @memberof CostBreakdownResponse
     */
    agent?: string;
    /**
     * 
     * @type {string}
     * @memberof CostBreakdownResponse
     */
    cachedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof CostBreakdownResponse
     */
    taskCount?: number;
    /**
     * 
     * @type {Array<TaskBreakdown>}
     * @memberof CostBreakdownResponse
     */
    tasks?: Array<TaskBreakdown>;
    /**
     * 
     * @type {number}
     * @memberof CostBreakdownResponse
     */
    totalCost?: number;
}

/**
 * Check if a given object implements the CostBreakdownResponse interface.
 */
export function instanceOfCostBreakdownResponse(value: object): value is CostBreakdownResponse {
    return true;
}

export function CostBreakdownResponseFromJSON(json: any): CostBreakdownResponse {
    return CostBreakdownResponseFromJSONTyped(json, false);
}

export function CostBreakdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostBreakdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'] == null ? undefined : json['agent'],
        'cachedAt': json['cachedAt'] == null ? undefined : json['cachedAt'],
        'taskCount': json['taskCount'] == null ? undefined : json['taskCount'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(TaskBreakdownFromJSON)),
        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
    };
}

export function CostBreakdownResponseToJSON(json: any): CostBreakdownResponse {
    return CostBreakdownResponseToJSONTyped(json, false);
}

export function CostBreakdownResponseToJSONTyped(value?: CostBreakdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': value['agent'],
        'cachedAt': value['cachedAt'],
        'taskCount': value['taskCount'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(TaskBreakdownToJSON)),
        'totalCost': value['totalCost'],
    };
}

