/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1StorageSpec } from './V1alpha1StorageSpec';
import {
    V1alpha1StorageSpecFromJSON,
    V1alpha1StorageSpecFromJSONTyped,
    V1alpha1StorageSpecToJSON,
    V1alpha1StorageSpecToJSONTyped,
} from './V1alpha1StorageSpec';
import type { V1PodSpec } from './V1PodSpec';
import {
    V1PodSpecFromJSON,
    V1PodSpecFromJSONTyped,
    V1PodSpecToJSON,
    V1PodSpecToJSONTyped,
} from './V1PodSpec';

/**
 * 
 * @export
 * @interface CreateAgentRequest
 */
export interface CreateAgentRequest {
    /**
     * AllowedTools restricts the agent to exactly these tools. REPLACES the default
     * built-in set rather than extending it, and connector tools are not auto-added.
     * Supports wildcards, e.g. "mcp__figma__*". Empty keeps default behavior.
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    allowedTools?: Array<string>;
    /**
     * optional KomputerConnector names to attach
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    connectors?: Array<string>;
    /**
     * DeleteTTL deletes the agent this long after creation, as a Go duration string
     * (e.g. "24h"). Absolute — it does not reset on wake. Empty means never auto-delete.
     * @type {string}
     * @memberof CreateAgentRequest
     */
    deleteTTL?: string;
    /**
     * DisallowedTools removes these tools; everything else stays available.
     * Takes precedence over AllowedTools. Supports wildcards.
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    disallowedTools?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    instructions: string;
    /**
     * Labels are user-defined key=value labels passed through to the agent CR.
     * Reserved-prefix keys (komputer.ai/*) are rejected except for
     * "komputer.ai/personal-agent" which is allow-listed.
     * @type {{ [key: string]: string; }}
     * @memberof CreateAgentRequest
     */
    labels?: { [key: string]: string; };
    /**
     * "", "Sleep", or "AutoDelete"
     * @type {string}
     * @memberof CreateAgentRequest
     */
    lifecycle?: string;
    /**
     * optional KomputerMemory names to attach
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    memories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    name: string;
    /**
     * optional, defaults to server default
     * @type {string}
     * @memberof CreateAgentRequest
     */
    namespace?: string;
    /**
     * set by manager MCP tool
     * @type {string}
     * @memberof CreateAgentRequest
     */
    officeManager?: string;
    /**
     * 
     * @type {V1PodSpec}
     * @memberof CreateAgentRequest
     */
    podSpec?: V1PodSpec;
    /**
     * queue priority; higher = admitted first
     * @type {number}
     * @memberof CreateAgentRequest
     */
    priority?: number;
    /**
     * "manager" or "" (default manager)
     * @type {string}
     * @memberof CreateAgentRequest
     */
    role?: string;
    /**
     * names of existing K8s Secrets to attach
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    secretRefs?: Array<string>;
    /**
     * optional KomputerSkill names to attach
     * @type {Array<string>}
     * @memberof CreateAgentRequest
     */
    skills?: Array<string>;
    /**
     * SleepTTL puts the agent to sleep after this long with no activity, as a Go
     * duration string (e.g. "30m", "2h"). Empty means never auto-sleep.
     * @type {string}
     * @memberof CreateAgentRequest
     */
    sleepTTL?: string;
    /**
     * 
     * @type {V1alpha1StorageSpec}
     * @memberof CreateAgentRequest
     */
    storage?: V1alpha1StorageSpec;
    /**
     * optional custom system prompt
     * @type {string}
     * @memberof CreateAgentRequest
     */
    systemPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    templateRef?: string;
}

/**
 * Check if a given object implements the CreateAgentRequest interface.
 */
export function instanceOfCreateAgentRequest(value: object): value is CreateAgentRequest {
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAgentRequestFromJSON(json: any): CreateAgentRequest {
    return CreateAgentRequestFromJSONTyped(json, false);
}

export function CreateAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedTools': json['allowedTools'] == null ? undefined : json['allowedTools'],
        'connectors': json['connectors'] == null ? undefined : json['connectors'],
        'deleteTTL': json['deleteTTL'] == null ? undefined : json['deleteTTL'],
        'disallowedTools': json['disallowedTools'] == null ? undefined : json['disallowedTools'],
        'instructions': json['instructions'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'lifecycle': json['lifecycle'] == null ? undefined : json['lifecycle'],
        'memories': json['memories'] == null ? undefined : json['memories'],
        'model': json['model'] == null ? undefined : json['model'],
        'name': json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'officeManager': json['officeManager'] == null ? undefined : json['officeManager'],
        'podSpec': json['podSpec'] == null ? undefined : V1PodSpecFromJSON(json['podSpec']),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'role': json['role'] == null ? undefined : json['role'],
        'secretRefs': json['secretRefs'] == null ? undefined : json['secretRefs'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'sleepTTL': json['sleepTTL'] == null ? undefined : json['sleepTTL'],
        'storage': json['storage'] == null ? undefined : V1alpha1StorageSpecFromJSON(json['storage']),
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'templateRef': json['templateRef'] == null ? undefined : json['templateRef'],
    };
}

export function CreateAgentRequestToJSON(json: any): CreateAgentRequest {
    return CreateAgentRequestToJSONTyped(json, false);
}

export function CreateAgentRequestToJSONTyped(value?: CreateAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedTools': value['allowedTools'],
        'connectors': value['connectors'],
        'deleteTTL': value['deleteTTL'],
        'disallowedTools': value['disallowedTools'],
        'instructions': value['instructions'],
        'labels': value['labels'],
        'lifecycle': value['lifecycle'],
        'memories': value['memories'],
        'model': value['model'],
        'name': value['name'],
        'namespace': value['namespace'],
        'officeManager': value['officeManager'],
        'podSpec': V1PodSpecToJSON(value['podSpec']),
        'priority': value['priority'],
        'role': value['role'],
        'secretRefs': value['secretRefs'],
        'skills': value['skills'],
        'sleepTTL': value['sleepTTL'],
        'storage': V1alpha1StorageSpecToJSON(value['storage']),
        'systemPrompt': value['systemPrompt'],
        'templateRef': value['templateRef'],
    };
}

