/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1KomputerSquadMember } from './V1alpha1KomputerSquadMember';
import {
    V1alpha1KomputerSquadMemberFromJSON,
    V1alpha1KomputerSquadMemberFromJSONTyped,
    V1alpha1KomputerSquadMemberToJSON,
    V1alpha1KomputerSquadMemberToJSONTyped,
} from './V1alpha1KomputerSquadMember';

/**
 * 
 * @export
 * @interface CreateSquadRequest
 */
export interface CreateSquadRequest {
    /**
     * 
     * @type {Array<V1alpha1KomputerSquadMember>}
     * @memberof CreateSquadRequest
     */
    members: Array<V1alpha1KomputerSquadMember>;
    /**
     * 
     * @type {string}
     * @memberof CreateSquadRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSquadRequest
     */
    namespace?: string;
    /**
     * duration string e.g. "10m"
     * @type {string}
     * @memberof CreateSquadRequest
     */
    orphanTTL?: string;
}

/**
 * Check if a given object implements the CreateSquadRequest interface.
 */
export function instanceOfCreateSquadRequest(value: object): value is CreateSquadRequest {
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSquadRequestFromJSON(json: any): CreateSquadRequest {
    return CreateSquadRequestFromJSONTyped(json, false);
}

export function CreateSquadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSquadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'members': ((json['members'] as Array<any>).map(V1alpha1KomputerSquadMemberFromJSON)),
        'name': json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'orphanTTL': json['orphanTTL'] == null ? undefined : json['orphanTTL'],
    };
}

export function CreateSquadRequestToJSON(json: any): CreateSquadRequest {
    return CreateSquadRequestToJSONTyped(json, false);
}

export function CreateSquadRequestToJSONTyped(value?: CreateSquadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'members': ((value['members'] as Array<any>).map(V1alpha1KomputerSquadMemberToJSON)),
        'name': value['name'],
        'namespace': value['namespace'],
        'orphanTTL': value['orphanTTL'],
    };
}

