/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1KomputerSquadMember } from './V1alpha1KomputerSquadMember';
import {
    V1alpha1KomputerSquadMemberFromJSON,
    V1alpha1KomputerSquadMemberFromJSONTyped,
    V1alpha1KomputerSquadMemberToJSON,
    V1alpha1KomputerSquadMemberToJSONTyped,
} from './V1alpha1KomputerSquadMember';

/**
 * 
 * @export
 * @interface PatchSquadRequest
 */
export interface PatchSquadRequest {
    /**
     * 
     * @type {Array<V1alpha1KomputerSquadMember>}
     * @memberof PatchSquadRequest
     */
    members?: Array<V1alpha1KomputerSquadMember>;
    /**
     * 
     * @type {string}
     * @memberof PatchSquadRequest
     */
    orphanTTL?: string;
}

/**
 * Check if a given object implements the PatchSquadRequest interface.
 */
export function instanceOfPatchSquadRequest(value: object): value is PatchSquadRequest {
    return true;
}

export function PatchSquadRequestFromJSON(json: any): PatchSquadRequest {
    return PatchSquadRequestFromJSONTyped(json, false);
}

export function PatchSquadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchSquadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(V1alpha1KomputerSquadMemberFromJSON)),
        'orphanTTL': json['orphanTTL'] == null ? undefined : json['orphanTTL'],
    };
}

export function PatchSquadRequestToJSON(json: any): PatchSquadRequest {
    return PatchSquadRequestToJSONTyped(json, false);
}

export function PatchSquadRequestToJSONTyped(value?: PatchSquadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(V1alpha1KomputerSquadMemberToJSON)),
        'orphanTTL': value['orphanTTL'],
    };
}

