/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateScheduleAgentSpec } from './CreateScheduleAgentSpec';
import {
    CreateScheduleAgentSpecFromJSON,
    CreateScheduleAgentSpecFromJSONTyped,
    CreateScheduleAgentSpecToJSON,
    CreateScheduleAgentSpecToJSONTyped,
} from './CreateScheduleAgentSpec';

/**
 * 
 * @export
 * @interface PatchScheduleRequest
 */
export interface PatchScheduleRequest {
    /**
     * 
     * @type {CreateScheduleAgentSpec}
     * @memberof PatchScheduleRequest
     */
    agent?: CreateScheduleAgentSpec;
    /**
     * 
     * @type {string}
     * @memberof PatchScheduleRequest
     */
    agentName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchScheduleRequest
     */
    autoDelete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchScheduleRequest
     */
    instructions?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchScheduleRequest
     */
    keepAgents?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchScheduleRequest
     */
    schedule?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchScheduleRequest
     */
    suspended?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchScheduleRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the PatchScheduleRequest interface.
 */
export function instanceOfPatchScheduleRequest(value: object): value is PatchScheduleRequest {
    return true;
}

export function PatchScheduleRequestFromJSON(json: any): PatchScheduleRequest {
    return PatchScheduleRequestFromJSONTyped(json, false);
}

export function PatchScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'] == null ? undefined : CreateScheduleAgentSpecFromJSON(json['agent']),
        'agentName': json['agentName'] == null ? undefined : json['agentName'],
        'autoDelete': json['autoDelete'] == null ? undefined : json['autoDelete'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'keepAgents': json['keepAgents'] == null ? undefined : json['keepAgents'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'suspended': json['suspended'] == null ? undefined : json['suspended'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function PatchScheduleRequestToJSON(json: any): PatchScheduleRequest {
    return PatchScheduleRequestToJSONTyped(json, false);
}

export function PatchScheduleRequestToJSONTyped(value?: PatchScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': CreateScheduleAgentSpecToJSON(value['agent']),
        'agentName': value['agentName'],
        'autoDelete': value['autoDelete'],
        'instructions': value['instructions'],
        'keepAgents': value['keepAgents'],
        'schedule': value['schedule'],
        'suspended': value['suspended'],
        'timezone': value['timezone'],
    };
}

