/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SquadResponse } from './SquadResponse';
import {
    SquadResponseFromJSON,
    SquadResponseFromJSONTyped,
    SquadResponseToJSON,
    SquadResponseToJSONTyped,
} from './SquadResponse';

/**
 * 
 * @export
 * @interface SquadListResponse
 */
export interface SquadListResponse {
    /**
     * 
     * @type {Array<SquadResponse>}
     * @memberof SquadListResponse
     */
    squads?: Array<SquadResponse>;
}

/**
 * Check if a given object implements the SquadListResponse interface.
 */
export function instanceOfSquadListResponse(value: object): value is SquadListResponse {
    return true;
}

export function SquadListResponseFromJSON(json: any): SquadListResponse {
    return SquadListResponseFromJSONTyped(json, false);
}

export function SquadListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SquadListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'squads': json['squads'] == null ? undefined : ((json['squads'] as Array<any>).map(SquadResponseFromJSON)),
    };
}

export function SquadListResponseToJSON(json: any): SquadListResponse {
    return SquadListResponseToJSONTyped(json, false);
}

export function SquadListResponseToJSONTyped(value?: SquadListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'squads': value['squads'] == null ? undefined : ((value['squads'] as Array<any>).map(SquadResponseToJSON)),
    };
}

