/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SquadMemberResponse } from './SquadMemberResponse';
import {
    SquadMemberResponseFromJSON,
    SquadMemberResponseFromJSONTyped,
    SquadMemberResponseToJSON,
    SquadMemberResponseToJSONTyped,
} from './SquadMemberResponse';

/**
 * 
 * @export
 * @interface SquadResponse
 */
export interface SquadResponse {
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<SquadMemberResponse>}
     * @memberof SquadResponse
     */
    members?: Array<SquadMemberResponse>;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    orphanTTL?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    orphanedSince?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    phase?: string;
    /**
     * 
     * @type {string}
     * @memberof SquadResponse
     */
    podName?: string;
}

/**
 * Check if a given object implements the SquadResponse interface.
 */
export function instanceOfSquadResponse(value: object): value is SquadResponse {
    return true;
}

export function SquadResponseFromJSON(json: any): SquadResponse {
    return SquadResponseFromJSONTyped(json, false);
}

export function SquadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SquadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(SquadMemberResponseFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'] == null ? undefined : json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'orphanTTL': json['orphanTTL'] == null ? undefined : json['orphanTTL'],
        'orphanedSince': json['orphanedSince'] == null ? undefined : json['orphanedSince'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'podName': json['podName'] == null ? undefined : json['podName'],
    };
}

export function SquadResponseToJSON(json: any): SquadResponse {
    return SquadResponseToJSONTyped(json, false);
}

export function SquadResponseToJSONTyped(value?: SquadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(SquadMemberResponseToJSON)),
        'message': value['message'],
        'name': value['name'],
        'namespace': value['namespace'],
        'orphanTTL': value['orphanTTL'],
        'orphanedSince': value['orphanedSince'],
        'phase': value['phase'],
        'podName': value['podName'],
    };
}

