/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SquadMemberResponse
 */
export interface SquadMemberResponse {
    /**
     * 
     * @type {string}
     * @memberof SquadMemberResponse
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SquadMemberResponse
     */
    ready?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SquadMemberResponse
     */
    taskStatus?: string;
}

/**
 * Check if a given object implements the SquadMemberResponse interface.
 */
export function instanceOfSquadMemberResponse(value: object): value is SquadMemberResponse {
    return true;
}

export function SquadMemberResponseFromJSON(json: any): SquadMemberResponse {
    return SquadMemberResponseFromJSONTyped(json, false);
}

export function SquadMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SquadMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'ready': json['ready'] == null ? undefined : json['ready'],
        'taskStatus': json['taskStatus'] == null ? undefined : json['taskStatus'],
    };
}

export function SquadMemberResponseToJSON(json: any): SquadMemberResponse {
    return SquadMemberResponseToJSONTyped(json, false);
}

export function SquadMemberResponseToJSONTyped(value?: SquadMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ready': value['ready'],
        'taskStatus': value['taskStatus'],
    };
}

