/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentEvent } from './AgentEvent';
import {
    AgentEventFromJSON,
    AgentEventFromJSONTyped,
    AgentEventToJSON,
    AgentEventToJSONTyped,
} from './AgentEvent';

/**
 * 
 * @export
 * @interface TaskBreakdown
 */
export interface TaskBreakdown {
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    cacheCreateTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    cacheReadTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskBreakdown
     */
    completedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    costUSD?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    durationMs?: number;
    /**
     * 
     * @type {Array<AgentEvent>}
     * @memberof TaskBreakdown
     */
    events?: Array<AgentEvent>;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    inputTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskBreakdown
     */
    instruction?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    outputTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskBreakdown
     */
    startedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskBreakdown
     */
    steer?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TaskBreakdown
     */
    turns?: number;
}

/**
 * Check if a given object implements the TaskBreakdown interface.
 */
export function instanceOfTaskBreakdown(value: object): value is TaskBreakdown {
    return true;
}

export function TaskBreakdownFromJSON(json: any): TaskBreakdown {
    return TaskBreakdownFromJSONTyped(json, false);
}

export function TaskBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheCreateTokens': json['cacheCreateTokens'] == null ? undefined : json['cacheCreateTokens'],
        'cacheReadTokens': json['cacheReadTokens'] == null ? undefined : json['cacheReadTokens'],
        'completedAt': json['completedAt'] == null ? undefined : json['completedAt'],
        'costUSD': json['costUSD'] == null ? undefined : json['costUSD'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(AgentEventFromJSON)),
        'index': json['index'] == null ? undefined : json['index'],
        'inputTokens': json['inputTokens'] == null ? undefined : json['inputTokens'],
        'instruction': json['instruction'] == null ? undefined : json['instruction'],
        'outputTokens': json['outputTokens'] == null ? undefined : json['outputTokens'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'steer': json['steer'] == null ? undefined : json['steer'],
        'turns': json['turns'] == null ? undefined : json['turns'],
    };
}

export function TaskBreakdownToJSON(json: any): TaskBreakdown {
    return TaskBreakdownToJSONTyped(json, false);
}

export function TaskBreakdownToJSONTyped(value?: TaskBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cacheCreateTokens': value['cacheCreateTokens'],
        'cacheReadTokens': value['cacheReadTokens'],
        'completedAt': value['completedAt'],
        'costUSD': value['costUSD'],
        'durationMs': value['durationMs'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(AgentEventToJSON)),
        'index': value['index'],
        'inputTokens': value['inputTokens'],
        'instruction': value['instruction'],
        'outputTokens': value['outputTokens'],
        'startedAt': value['startedAt'],
        'steer': value['steer'],
        'turns': value['turns'],
    };
}

