/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerScheduleResponse
 */
export interface TriggerScheduleResponse {
    /**
     * 
     * @type {string}
     * @memberof TriggerScheduleResponse
     */
    agentName?: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerScheduleResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerScheduleResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TriggerScheduleResponse interface.
 */
export function instanceOfTriggerScheduleResponse(value: object): value is TriggerScheduleResponse {
    return true;
}

export function TriggerScheduleResponseFromJSON(json: any): TriggerScheduleResponse {
    return TriggerScheduleResponseFromJSONTyped(json, false);
}

export function TriggerScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agentName': json['agentName'] == null ? undefined : json['agentName'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TriggerScheduleResponseToJSON(json: any): TriggerScheduleResponse {
    return TriggerScheduleResponseToJSONTyped(json, false);
}

export function TriggerScheduleResponseToJSONTyped(value?: TriggerScheduleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentName': value['agentName'],
        'name': value['name'],
        'status': value['status'],
    };
}

