/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConnectorRequest
 */
export interface UpdateConnectorRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateConnectorRequest
     */
    namespace?: string;
    /**
     * new auth token; replaces the value in the connector's secret
     * @type {string}
     * @memberof UpdateConnectorRequest
     */
    token: string;
}

/**
 * Check if a given object implements the UpdateConnectorRequest interface.
 */
export function instanceOfUpdateConnectorRequest(value: object): value is UpdateConnectorRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function UpdateConnectorRequestFromJSON(json: any): UpdateConnectorRequest {
    return UpdateConnectorRequestFromJSONTyped(json, false);
}

export function UpdateConnectorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConnectorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'token': json['token'],
    };
}

export function UpdateConnectorRequestToJSON(json: any): UpdateConnectorRequest {
    return UpdateConnectorRequestToJSONTyped(json, false);
}

export function UpdateConnectorRequestToJSONTyped(value?: UpdateConnectorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'token': value['token'],
    };
}

