/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1KomputerAgentSpec } from './V1alpha1KomputerAgentSpec';
import {
    V1alpha1KomputerAgentSpecFromJSON,
    V1alpha1KomputerAgentSpecFromJSONTyped,
    V1alpha1KomputerAgentSpecToJSON,
    V1alpha1KomputerAgentSpecToJSONTyped,
} from './V1alpha1KomputerAgentSpec';
import type { V1alpha1KomputerSquadMemberRef } from './V1alpha1KomputerSquadMemberRef';
import {
    V1alpha1KomputerSquadMemberRefFromJSON,
    V1alpha1KomputerSquadMemberRefFromJSONTyped,
    V1alpha1KomputerSquadMemberRefToJSON,
    V1alpha1KomputerSquadMemberRefToJSONTyped,
} from './V1alpha1KomputerSquadMemberRef';

/**
 * 
 * @export
 * @interface V1alpha1KomputerSquadMember
 */
export interface V1alpha1KomputerSquadMember {
    /**
     * Exactly one of Ref or Spec must be set.
     * @type {V1alpha1KomputerSquadMemberRef}
     * @memberof V1alpha1KomputerSquadMember
     */
    ref?: V1alpha1KomputerSquadMemberRef;
    /**
     * 
     * @type {V1alpha1KomputerAgentSpec}
     * @memberof V1alpha1KomputerSquadMember
     */
    spec?: V1alpha1KomputerAgentSpec;
}

/**
 * Check if a given object implements the V1alpha1KomputerSquadMember interface.
 */
export function instanceOfV1alpha1KomputerSquadMember(value: object): value is V1alpha1KomputerSquadMember {
    return true;
}

export function V1alpha1KomputerSquadMemberFromJSON(json: any): V1alpha1KomputerSquadMember {
    return V1alpha1KomputerSquadMemberFromJSONTyped(json, false);
}

export function V1alpha1KomputerSquadMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1KomputerSquadMember {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'] == null ? undefined : V1alpha1KomputerSquadMemberRefFromJSON(json['ref']),
        'spec': json['spec'] == null ? undefined : V1alpha1KomputerAgentSpecFromJSON(json['spec']),
    };
}

export function V1alpha1KomputerSquadMemberToJSON(json: any): V1alpha1KomputerSquadMember {
    return V1alpha1KomputerSquadMemberToJSONTyped(json, false);
}

export function V1alpha1KomputerSquadMemberToJSONTyped(value?: V1alpha1KomputerSquadMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': V1alpha1KomputerSquadMemberRefToJSON(value['ref']),
        'spec': V1alpha1KomputerAgentSpecToJSON(value['spec']),
    };
}

