/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1alpha1AgentLifecycle = {
    AgentLifecycleDefault: '',
    AgentLifecycleSleep: 'Sleep',
    AgentLifecycleAutoDelete: 'AutoDelete'
} as const;
export type V1alpha1AgentLifecycle = typeof V1alpha1AgentLifecycle[keyof typeof V1alpha1AgentLifecycle];


export function instanceOfV1alpha1AgentLifecycle(value: any): boolean {
    for (const key in V1alpha1AgentLifecycle) {
        if (Object.prototype.hasOwnProperty.call(V1alpha1AgentLifecycle, key)) {
            if (V1alpha1AgentLifecycle[key as keyof typeof V1alpha1AgentLifecycle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1alpha1AgentLifecycleFromJSON(json: any): V1alpha1AgentLifecycle {
    return V1alpha1AgentLifecycleFromJSONTyped(json, false);
}

export function V1alpha1AgentLifecycleFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1AgentLifecycle {
    return json as V1alpha1AgentLifecycle;
}

export function V1alpha1AgentLifecycleToJSON(value?: V1alpha1AgentLifecycle | null): any {
    return value as any;
}

export function V1alpha1AgentLifecycleToJSONTyped(value: any, ignoreDiscriminator: boolean): V1alpha1AgentLifecycle {
    return value as V1alpha1AgentLifecycle;
}

