/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1AgentLifecycle } from './V1alpha1AgentLifecycle';
import {
    V1alpha1AgentLifecycleFromJSON,
    V1alpha1AgentLifecycleFromJSONTyped,
    V1alpha1AgentLifecycleToJSON,
    V1alpha1AgentLifecycleToJSONTyped,
} from './V1alpha1AgentLifecycle';
import type { V1alpha1StorageSpec } from './V1alpha1StorageSpec';
import {
    V1alpha1StorageSpecFromJSON,
    V1alpha1StorageSpecFromJSONTyped,
    V1alpha1StorageSpecToJSON,
    V1alpha1StorageSpecToJSONTyped,
} from './V1alpha1StorageSpec';
import type { V1Duration } from './V1Duration';
import {
    V1DurationFromJSON,
    V1DurationFromJSONTyped,
    V1DurationToJSON,
    V1DurationToJSONTyped,
} from './V1Duration';
import type { V1PodSpec } from './V1PodSpec';
import {
    V1PodSpecFromJSON,
    V1PodSpecFromJSONTyped,
    V1PodSpecToJSON,
    V1PodSpecToJSONTyped,
} from './V1PodSpec';

/**
 * 
 * @export
 * @interface V1alpha1ScheduleAgentSpec
 */
export interface V1alpha1ScheduleAgentSpec {
    /**
     * AllowedTools restricts the agent to exactly these tools. When empty, the
     * default built-in tool set is used and all tools from attached connectors
     * are permitted.
     * 
     * Setting this REPLACES the default set rather than extending it, so an
     * agent given only ["Read"] loses Bash, Write, Edit and the rest. Connector
     * tools are not auto-added either — list them explicitly, e.g.
     * "mcp__figma__*" for a whole connector or "mcp__figma__get_design_context"
     * for a single tool.
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    allowedTools?: Array<string>;
    /**
     * Connectors is a list of KomputerConnector names to attach to this agent.
     * Names can be "name" (same namespace) or "namespace/name" (cross-namespace).
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    connectors?: Array<string>;
    /**
     * DeleteTTL deletes the entire agent (pod + PVC) once this long has elapsed since
     * metadata.creationTimestamp. This is an absolute lifetime cap: unlike SleepTTL it
     * does not reset on wake and applies in every phase, including Sleeping.
     * Unset (default) means the agent never auto-deletes.
     * Overrides the template's deleteTTL when set.
     * +optional
     * @type {V1Duration}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    deleteTTL?: V1Duration;
    /**
     * DisallowedTools removes these tools from the agent. Purely subtractive:
     * the default built-ins and all connector tools remain available except
     * what is named here. Takes precedence over AllowedTools.
     * Supports wildcards, e.g. "mcp__figma__*".
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    disallowedTools?: Array<string>;
    /**
     * Labels are user-defined key=value labels attached to this agent and
     * propagated to all child resources (Pod, PVC, ConfigMap, Service).
     * Keys starting with "komputer.ai/" are reserved for system labels and
     * should not be set directly through the API.
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    labels?: { [key: string]: string; };
    /**
     * Lifecycle controls what happens after task completion.
     * Empty (default) keeps the pod running, "Sleep" deletes the pod but keeps the PVC,
     * "AutoDelete" deletes the entire agent after task completion.
     * +kubebuilder:validation:Enum="";Sleep;AutoDelete
     * +optional
     * @type {V1alpha1AgentLifecycle}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    lifecycle?: V1alpha1AgentLifecycle;
    /**
     * Memories is a list of KomputerMemory names to attach to this agent.
     * Names can be "name" (same namespace) or "namespace/name" (cross-namespace).
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    memories?: Array<string>;
    /**
     * Model is the Claude model to use.
     * +kubebuilder:default="claude-sonnet-4-6"
     * @type {string}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    model?: string;
    /**
     * PodSpec, when set, overrides the template's PodSpec for this agent.
     * Container fields are merged by name; non-zero fields from this PodSpec
     * override the template's container fields. Takes effect on next pod start
     * (existing pods are not mutated).
     * +optional
     * @type {V1PodSpec}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    podSpec?: V1PodSpec;
    /**
     * Priority controls admission order when the template's maxConcurrentAgents
     * limit is reached. Higher number = admitted first (matches K8s PodPriority).
     * Ties broken by creationTimestamp (older first). Defaults to 0.
     * +kubebuilder:default=0
     * +optional
     * @type {number}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    priority?: number;
    /**
     * Role is "manager" or "worker". Managers get orchestration tools.
     * Role is "manager" or "worker". Defaults to "manager" for top-level agents.
     * Sub-agents created by managers are explicitly set to "worker".
     * +kubebuilder:default="manager"
     * +kubebuilder:validation:Enum=worker;manager
     * +optional
     * @type {string}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    role?: string;
    /**
     * Secrets is a list of K8s Secret names containing agent-specific secrets.
     * Each key in each secret is injected as an env var into the agent pod.
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    secrets?: Array<string>;
    /**
     * Skills is a list of KomputerSkill names to attach to this agent.
     * Names can be "name" (same namespace) or "namespace/name" (cross-namespace).
     * +optional
     * @type {Array<string>}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    skills?: Array<string>;
    /**
     * SleepTTL puts the agent to sleep (pod deleted, PVC preserved) once it has been
     * idle for this long. Idle is measured from Status.LastActivityAt, so the clock
     * only starts once a task has actually started, and any later task event or wake
     * resets it. Never fires while a task is in progress, and an agent that has never
     * run a task is never auto-slept (use DeleteTTL to reclaim those).
     * Unset (default) means the agent never auto-sleeps.
     * Overrides the template's sleepTTL when set.
     * +optional
     * @type {V1Duration}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    sleepTTL?: V1Duration;
    /**
     * Storage, when set, overrides the template's storage settings for this agent.
     * Existing PVCs are expanded in place when the storage class supports it.
     * +optional
     * @type {V1alpha1StorageSpec}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    storage?: V1alpha1StorageSpec;
    /**
     * SystemPrompt is a custom system prompt provided by the user, appended to the internal prompt.
     * +optional
     * @type {string}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    systemPrompt?: string;
    /**
     * TaskTimeout cancels the agent's running task once it has been running for this
     * long. The clock starts when a task starts (Status.TaskStartedAt) and never
     * resets — steering a task does not extend it — so this is a hard wall-clock cap
     * on a single task, not an idle timeout.
     * 
     * Only the task is cancelled; the agent itself stays alive and any configured
     * Lifecycle (Sleep / AutoDelete) then applies as it would after any other task end.
     * Unset (default) means tasks run without a time limit.
     * Overrides the template's taskTimeout when set.
     * +optional
     * @type {V1Duration}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    taskTimeout?: V1Duration;
    /**
     * TemplateRef is the name of the KomputerAgentTemplate to use.
     * +kubebuilder:default="default"
     * @type {string}
     * @memberof V1alpha1ScheduleAgentSpec
     */
    templateRef?: string;
}



/**
 * Check if a given object implements the V1alpha1ScheduleAgentSpec interface.
 */
export function instanceOfV1alpha1ScheduleAgentSpec(value: object): value is V1alpha1ScheduleAgentSpec {
    return true;
}

export function V1alpha1ScheduleAgentSpecFromJSON(json: any): V1alpha1ScheduleAgentSpec {
    return V1alpha1ScheduleAgentSpecFromJSONTyped(json, false);
}

export function V1alpha1ScheduleAgentSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1ScheduleAgentSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedTools': json['allowedTools'] == null ? undefined : json['allowedTools'],
        'connectors': json['connectors'] == null ? undefined : json['connectors'],
        'deleteTTL': json['deleteTTL'] == null ? undefined : V1DurationFromJSON(json['deleteTTL']),
        'disallowedTools': json['disallowedTools'] == null ? undefined : json['disallowedTools'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'lifecycle': json['lifecycle'] == null ? undefined : V1alpha1AgentLifecycleFromJSON(json['lifecycle']),
        'memories': json['memories'] == null ? undefined : json['memories'],
        'model': json['model'] == null ? undefined : json['model'],
        'podSpec': json['podSpec'] == null ? undefined : V1PodSpecFromJSON(json['podSpec']),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'role': json['role'] == null ? undefined : json['role'],
        'secrets': json['secrets'] == null ? undefined : json['secrets'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'sleepTTL': json['sleepTTL'] == null ? undefined : V1DurationFromJSON(json['sleepTTL']),
        'storage': json['storage'] == null ? undefined : V1alpha1StorageSpecFromJSON(json['storage']),
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'taskTimeout': json['taskTimeout'] == null ? undefined : V1DurationFromJSON(json['taskTimeout']),
        'templateRef': json['templateRef'] == null ? undefined : json['templateRef'],
    };
}

export function V1alpha1ScheduleAgentSpecToJSON(json: any): V1alpha1ScheduleAgentSpec {
    return V1alpha1ScheduleAgentSpecToJSONTyped(json, false);
}

export function V1alpha1ScheduleAgentSpecToJSONTyped(value?: V1alpha1ScheduleAgentSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedTools': value['allowedTools'],
        'connectors': value['connectors'],
        'deleteTTL': V1DurationToJSON(value['deleteTTL']),
        'disallowedTools': value['disallowedTools'],
        'labels': value['labels'],
        'lifecycle': V1alpha1AgentLifecycleToJSON(value['lifecycle']),
        'memories': value['memories'],
        'model': value['model'],
        'podSpec': V1PodSpecToJSON(value['podSpec']),
        'priority': value['priority'],
        'role': value['role'],
        'secrets': value['secrets'],
        'skills': value['skills'],
        'sleepTTL': V1DurationToJSON(value['sleepTTL']),
        'storage': V1alpha1StorageSpecToJSON(value['storage']),
        'systemPrompt': value['systemPrompt'],
        'taskTimeout': V1DurationToJSON(value['taskTimeout']),
        'templateRef': value['templateRef'],
    };
}

