/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1alpha1KomputerSquadMemberRef
 */
export interface V1alpha1KomputerSquadMemberRef {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1KomputerSquadMemberRef
     */
    name?: string;
    /**
     * defaults to squad's namespace
     * @type {string}
     * @memberof V1alpha1KomputerSquadMemberRef
     */
    namespace?: string;
}

/**
 * Check if a given object implements the V1alpha1KomputerSquadMemberRef interface.
 */
export function instanceOfV1alpha1KomputerSquadMemberRef(value: object): value is V1alpha1KomputerSquadMemberRef {
    return true;
}

export function V1alpha1KomputerSquadMemberRefFromJSON(json: any): V1alpha1KomputerSquadMemberRef {
    return V1alpha1KomputerSquadMemberRefFromJSONTyped(json, false);
}

export function V1alpha1KomputerSquadMemberRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1KomputerSquadMemberRef {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
    };
}

export function V1alpha1KomputerSquadMemberRefToJSON(json: any): V1alpha1KomputerSquadMemberRef {
    return V1alpha1KomputerSquadMemberRefToJSONTyped(json, false);
}

export function V1alpha1KomputerSquadMemberRefToJSONTyped(value?: V1alpha1KomputerSquadMemberRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'namespace': value['namespace'],
    };
}

