/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Duration
 */
export interface V1Duration {
    /**
     * 
     * @type {V1DurationTimeDurationEnum}
     * @memberof V1Duration
     */
    timeDuration?: V1DurationTimeDurationEnum;
}


/**
 * @export
 */
export const V1DurationTimeDurationEnum = {
    minDuration: -9223372036854775808,
    maxDuration: 9223372036854775807,
    Nanosecond: 1,
    Microsecond: 1000,
    Millisecond: 1000000,
    Second: 1000000000,
    Minute: 60000000000,
    Hour: 3600000000000
} as const;
export type V1DurationTimeDurationEnum = typeof V1DurationTimeDurationEnum[keyof typeof V1DurationTimeDurationEnum];


/**
 * Check if a given object implements the V1Duration interface.
 */
export function instanceOfV1Duration(value: object): value is V1Duration {
    return true;
}

export function V1DurationFromJSON(json: any): V1Duration {
    return V1DurationFromJSONTyped(json, false);
}

export function V1DurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Duration {
    if (json == null) {
        return json;
    }
    return {
        
        'timeDuration': json['time.Duration'] == null ? undefined : json['time.Duration'],
    };
}

export function V1DurationToJSON(json: any): V1Duration {
    return V1DurationToJSONTyped(json, false);
}

export function V1DurationToJSONTyped(value?: V1Duration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time.Duration': value['timeDuration'],
    };
}

