/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { K8sIoApiCoreV1ResourceClaim } from './K8sIoApiCoreV1ResourceClaim';
import {
    K8sIoApiCoreV1ResourceClaimFromJSON,
    K8sIoApiCoreV1ResourceClaimFromJSONTyped,
    K8sIoApiCoreV1ResourceClaimToJSON,
    K8sIoApiCoreV1ResourceClaimToJSONTyped,
} from './K8sIoApiCoreV1ResourceClaim';

/**
 * 
 * @export
 * @interface V1ResourceRequirements
 */
export interface V1ResourceRequirements {
    /**
     * Claims lists the names of resources, defined in spec.resourceClaims,
     * that are used by this container.
     * 
     * This field depends on the
     * DynamicResourceAllocation feature gate.
     * 
     * This field is immutable. It can only be set for containers.
     * 
     * +listType=map
     * +listMapKey=name
     * +featureGate=DynamicResourceAllocation
     * +optional
     * @type {Array<K8sIoApiCoreV1ResourceClaim>}
     * @memberof V1ResourceRequirements
     */
    claims?: Array<K8sIoApiCoreV1ResourceClaim>;
    /**
     * Limits describes the maximum amount of compute resources allowed.
     * More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1ResourceRequirements
     */
    limits?: { [key: string]: string; };
    /**
     * Requests describes the minimum amount of compute resources required.
     * If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
     * otherwise to an implementation-defined value. Requests cannot exceed Limits.
     * More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1ResourceRequirements
     */
    requests?: { [key: string]: string; };
}

/**
 * Check if a given object implements the V1ResourceRequirements interface.
 */
export function instanceOfV1ResourceRequirements(value: object): value is V1ResourceRequirements {
    return true;
}

export function V1ResourceRequirementsFromJSON(json: any): V1ResourceRequirements {
    return V1ResourceRequirementsFromJSONTyped(json, false);
}

export function V1ResourceRequirementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ResourceRequirements {
    if (json == null) {
        return json;
    }
    return {
        
        'claims': json['claims'] == null ? undefined : ((json['claims'] as Array<any>).map(K8sIoApiCoreV1ResourceClaimFromJSON)),
        'limits': json['limits'] == null ? undefined : json['limits'],
        'requests': json['requests'] == null ? undefined : json['requests'],
    };
}

export function V1ResourceRequirementsToJSON(json: any): V1ResourceRequirements {
    return V1ResourceRequirementsToJSONTyped(json, false);
}

export function V1ResourceRequirementsToJSONTyped(value?: V1ResourceRequirements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'claims': value['claims'] == null ? undefined : ((value['claims'] as Array<any>).map(K8sIoApiCoreV1ResourceClaimToJSON)),
        'limits': value['limits'],
        'requests': value['requests'],
    };
}

