/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1VolumeResourceRequirements
 */
export interface V1VolumeResourceRequirements {
    /**
     * Limits describes the maximum amount of compute resources allowed.
     * More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1VolumeResourceRequirements
     */
    limits?: { [key: string]: string; };
    /**
     * Requests describes the minimum amount of compute resources required.
     * If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
     * otherwise to an implementation-defined value. Requests cannot exceed Limits.
     * More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1VolumeResourceRequirements
     */
    requests?: { [key: string]: string; };
}

/**
 * Check if a given object implements the V1VolumeResourceRequirements interface.
 */
export function instanceOfV1VolumeResourceRequirements(value: object): value is V1VolumeResourceRequirements {
    return true;
}

export function V1VolumeResourceRequirementsFromJSON(json: any): V1VolumeResourceRequirements {
    return V1VolumeResourceRequirementsFromJSONTyped(json, false);
}

export function V1VolumeResourceRequirementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1VolumeResourceRequirements {
    if (json == null) {
        return json;
    }
    return {
        
        'limits': json['limits'] == null ? undefined : json['limits'],
        'requests': json['requests'] == null ? undefined : json['requests'],
    };
}

export function V1VolumeResourceRequirementsToJSON(json: any): V1VolumeResourceRequirements {
    return V1VolumeResourceRequirementsToJSONTyped(json, false);
}

export function V1VolumeResourceRequirementsToJSONTyped(value?: V1VolumeResourceRequirements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limits': value['limits'],
        'requests': value['requests'],
    };
}

